#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
===============================================================================
GWAS2m STEP 14
LOCUS-TO-MECHANISM INTERPRETATION
===============================================================================

PURPOSE
-------
Turn fine-mapped GWAS loci into transparent mechanistic interpretations by
integrating the outputs already generated by GWAS2m:

    Step06  fine-mapping / PIP / credible-set membership
    Step07  VEP coding + transcript + protein consequence
    Step10  SpliceAI + Pangolin integrated splicing evidence
    Step11  GTEx eQTL / sQTL colocalisation screen
    Step13  Open Targets/Gentropy agreement/disagreement status

The script is phenotype-agnostic:

    python Step14_Interpret_Variant_Mechanisms.py \
        --phenotype migraine \
        --ancestry EUR

    python Step14_Interpret_Variant_Mechanisms.py \
        --phenotype coronary_artery_disease \
        --ancestry EUR

IMPORTANT
---------
This step DOES NOT invent causality.

It reports observed/predicted evidence and assigns transparent descriptive
mechanism classes. Current Step11 LCLPP remains a screening statistic unless
formal colocalisation is added later.

OPTIONAL EXTERNAL RESOURCES
---------------------------
Step14 automatically looks in:

    resources/mechanism/

for:

    clinvar.tsv.gz
    alphamissense.tsv.gz
    cadd.tsv.gz
    gene_constraint.tsv.gz
    mendelian_gene_disease.tsv.gz

or equivalent .tsv files.

Expected minimal schemas:

ClinVar:
    VARIANT_KEY
    CLINVAR_SIGNIFICANCE
    CLINVAR_CONDITION
    CLINVAR_REVIEW_STATUS

AlphaMissense:
    VARIANT_KEY
    ALPHAMISSENSE_SCORE
    ALPHAMISSENSE_CLASS

CADD:
    VARIANT_KEY
    CADD_PHRED

Gene constraint:
    GENE_ID and/or SYMBOL
    LOEUF
    PLI

Mendelian gene-disease:
    GENE_ID and/or SYMBOL
    MENDELIAN_DISEASE
    MENDELIAN_SOURCE
    MENDELIAN_EVIDENCE

These are OPTIONAL. Missing resources are explicitly reported instead of
being treated as negative evidence.

OUTPUT
------
14_mechanism/<phenotype>/<ancestry>/

    all_variant_mechanisms.tsv.gz
    coding_variant_mechanisms.tsv
    noncoding_variant_mechanisms.tsv
    unresolved_variant_mechanisms.tsv
    locus_mechanism_summary.tsv
    study_mechanism_summary.tsv
    top_mechanistic_candidates.tsv
    mechanism_resource_status.tsv
    mechanism_summary.json

Per-study outputs are also written under:

    14_mechanism/<phenotype>/<ancestry>/<GCST>/

===============================================================================
"""

from __future__ import annotations

import argparse
import json
import re
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd


VERSION = "1.0.0"

DEFAULT_EQTL_SCREEN = 0.01
DEFAULT_SQTL_SCREEN = 0.01
DEFAULT_SPLICEAI_SUPPORT = 0.20


ANCESTRY = {
    "eur": ("EUR", "European"),
    "european": ("EUR", "European"),
    "afr": ("AFR", "African"),
    "african": ("AFR", "African"),
    "eas": ("EAS", "East Asian"),
    "east asian": ("EAS", "East Asian"),
    "sas": ("SAS", "South Asian"),
    "south asian": ("SAS", "South Asian"),
    "amr": ("AMR", "Hispanic or Latin American"),
    "hispanic": ("AMR", "Hispanic or Latin American"),
    "latino": ("AMR", "Hispanic or Latin American"),
    "hispanic or latin american": ("AMR", "Hispanic or Latin American"),
}


# =============================================================================
# HELPERS
# =============================================================================

def norm(value):
    return re.sub(
        r"\s+",
        " ",
        re.sub(r"[^a-z0-9]+", " ", str(value).lower()),
    ).strip()


def slug(value):
    return norm(value).replace(" ", "_")


def ancestry_info(value):
    key = norm(value)
    if key not in ANCESTRY:
        raise SystemExit(
            f"Unsupported ancestry {value!r}. "
            "Use EUR, AFR, EAS, SAS, or AMR."
        )
    return ANCESTRY[key]


def section(title):
    print()
    print("=" * 150)
    print(title)
    print("=" * 150)


def safe_numeric(value):
    return pd.to_numeric(value, errors="coerce")


def boolish(value):
    if isinstance(value, (bool, np.bool_)):
        return bool(value)

    if value is None:
        return False

    try:
        if pd.isna(value):
            return False
    except Exception:
        pass

    return str(value).strip().lower() in {
        "1", "true", "t", "yes", "y"
    }


def canonical_chr(value):
    if value is None:
        return ""

    try:
        if pd.isna(value):
            return ""
    except Exception:
        pass

    x = str(value).strip()
    x = re.sub(r"^chr", "", x, flags=re.I)

    if x.endswith(".0"):
        x = x[:-2]

    return x.upper()


def canonical_variant_from_parts(chrom, pos, ref, alt):
    chrom = canonical_chr(chrom)

    try:
        pos = str(int(float(pos)))
    except Exception:
        return ""

    ref = str(ref).strip().upper()
    alt = str(alt).strip().upper()

    if not chrom or not ref or not alt:
        return ""

    return f"{chrom}:{pos}:{ref}:{alt}"


def canonical_variant(value):
    if value is None:
        return ""

    try:
        if pd.isna(value):
            return ""
    except Exception:
        pass

    x = re.sub(r"^chr", "", str(value).strip(), flags=re.I)
    parts = re.split(r"[:_]", x)

    if len(parts) < 4:
        return ""

    return canonical_variant_from_parts(
        parts[0],
        parts[1],
        parts[2],
        parts[3],
    )


def gene_base(value):
    if value is None:
        return ""

    try:
        if pd.isna(value):
            return ""
    except Exception:
        pass

    x = str(value).strip()

    if x.lower() in {
        "", "nan", "none", "na", "null", "."
    }:
        return ""

    match = re.search(r"(ENSG\d+)", x, flags=re.I)

    return (
        match.group(1).upper()
        if match
        else x
    )


def first_existing(columns, candidates):
    lower = {
        str(c).lower(): c
        for c in columns
    }

    for candidate in candidates:
        if candidate in columns:
            return candidate

        if candidate.lower() in lower:
            return lower[candidate.lower()]

    return None


def join_unique(values, sep=";"):
    out = []

    for value in values:
        if value is None:
            continue

        try:
            if pd.isna(value):
                continue
        except Exception:
            pass

        for token in str(value).split(";"):
            token = token.strip()

            if token and token not in out:
                out.append(token)

    return sep.join(out)


def json_safe(obj):
    if isinstance(obj, np.integer):
        return int(obj)

    if isinstance(obj, np.floating):
        return None if np.isnan(obj) else float(obj)

    if isinstance(obj, np.bool_):
        return bool(obj)

    if isinstance(obj, np.ndarray):
        return obj.tolist()

    if isinstance(obj, Path):
        return str(obj)

    try:
        if pd.isna(obj):
            return None
    except Exception:
        pass

    raise TypeError(
        f"Object of type {type(obj).__name__} "
        "is not JSON serialisable"
    )


def show(df, title, n=60):
    section(title)

    if df is None or df.empty:
        print("(no rows)")
        return

    x = df.head(n)

    with pd.option_context(
        "display.max_rows", None,
        "display.max_columns", None,
        "display.width", 600,
        "display.max_colwidth", 80,
        "display.expand_frame_repr", False,
        "display.float_format", lambda v: f"{v:.6g}",
    ):
        print(x.to_string(index=False))

    if len(df) > len(x):
        print(f"\n[showing {len(x):,}/{len(df):,} rows]")


def read_table(path):
    if not path.exists() or path.stat().st_size == 0:
        return pd.DataFrame()

    return pd.read_csv(
        path,
        sep="\t",
        compression="infer",
        low_memory=False,
    )


# =============================================================================
# PATHS
# =============================================================================

def make_paths(root, phenotype, ancestry_label):
    p = slug(phenotype)
    a = slug(ancestry_label)

    return {
        "S06": root / "06_finemapping" / p / a,
        "S07": root / "07_annotation" / p / a,
        "S10": root / "10_pangolin" / p / a,
        "S11": root / "11_coloc" / p / a,
        "S13": root / "13_opentargets_detail" / p / a,
        "OUT": root / "14_mechanism" / p / a,
        "RESOURCES": root / "resources" / "mechanism",
    }


def discover_studies(paths):
    studies = set()

    for key in ["S06", "S07", "S10", "S11"]:
        base = paths[key]

        if not base.exists():
            continue

        for path in base.glob("GCST*"):
            if (
                path.is_dir()
                and
                re.fullmatch(r"GCST\d+", path.name)
            ):
                studies.add(path.name)

    return sorted(studies)


# =============================================================================
# STEP07
# =============================================================================

def load_step07(paths, study):
    path = (
        paths["S07"]
        /
        study
        /
        f"{study}_VEP_variant_summary.tsv"
    )

    x = read_table(path)

    if x.empty:
        return x

    required = [
        "LOCUS_ID",
        "CHR",
        "REFERENCE_POS",
        "REFERENCE_REF",
        "REFERENCE_ALT",
        "PIP",
    ]

    missing = [
        c
        for c in required
        if c not in x.columns
    ]

    if missing:
        raise RuntimeError(
            f"Step07 file missing columns {missing}: {path}"
        )

    x = x.copy()

    x["VARIANT_KEY"] = [
        canonical_variant_from_parts(c, p, r, a)
        for c, p, r, a
        in zip(
            x["CHR"],
            x["REFERENCE_POS"],
            x["REFERENCE_REF"],
            x["REFERENCE_ALT"],
        )
    ]

    x["PIP"] = safe_numeric(x["PIP"])

    if "IN_95_CREDIBLE_SET" in x.columns:
        x["IN_95_CREDIBLE_SET"] = x[
            "IN_95_CREDIBLE_SET"
        ].map(boolish)

    else:
        x["IN_95_CREDIBLE_SET"] = False

    return x


# =============================================================================
# STEP10
# =============================================================================

def load_step10(paths, study):
    path = (
        paths["S10"]
        /
        study
        /
        f"{study}_SpliceAI_Pangolin_integrated.tsv"
    )

    x = read_table(path)

    if x.empty:
        return x

    if "VARIANT_KEY" not in x.columns:
        needed = [
            "CHR",
            "REFERENCE_POS",
            "REFERENCE_REF",
            "REFERENCE_ALT",
        ]

        if all(c in x.columns for c in needed):
            x["VARIANT_KEY"] = [
                canonical_variant_from_parts(c, p, r, a)
                for c, p, r, a
                in zip(
                    x["CHR"],
                    x["REFERENCE_POS"],
                    x["REFERENCE_REF"],
                    x["REFERENCE_ALT"],
                )
            ]

        else:
            return pd.DataFrame()

    keep = [
        c
        for c in [
            "VARIANT_KEY",
            "VEP_ID",
            "SPLICEAI_MAX_DS",
            "SPLICEAI_MAX_EVENT",
            "SPLICEAI_GENE",
            "PANGOLIN_GENE",
            "PANGOLIN_MAX_ABS",
            "PANGOLIN_MAX_SIGNED",
            "PANGOLIN_MAX_EVENT",
            "PANGOLIN_MAX_POSITION",
            "PANGOLIN_PERCENTILE",
            "PANGOLIN_TOP_10PCT",
            "PANGOLIN_TOP_5PCT",
            "PANGOLIN_TOP_1PCT",
            "PANGOLIN_ALL_GENES",
            "HAS_SPLICEAI_GE_0_20",
            "HAS_SPLICEAI_GE_0_50",
            "HAS_GTEX_SQTL_BOOL",
            "HAS_VEP_SPLICE",
            "N_SPLICE_EVIDENCE_SOURCES",
            "SPLICE_EVIDENCE_COMBINATION",
            "SPLICE_PRIORITY_INSPECTION",
        ]
        if c in x.columns
    ]

    x = x[keep].copy()

    x = x.drop_duplicates(
        "VARIANT_KEY",
        keep="first",
    )

    return x


# =============================================================================
# STEP11
# =============================================================================

def effective_qtl_gene(row):
    gene = gene_base(
        row.get("QTL_GENE")
    )

    if gene:
        return gene

    return gene_base(
        row.get("QTL_PHENOTYPE")
    )


def load_step11(paths, study):
    path = (
        paths["S11"]
        /
        study
        /
        f"{study}_GTEx_SuSiE_gene_tissue_colocalization.tsv"
    )

    x = read_table(path)

    if x.empty:
        return x

    if "LOCUS_ID" not in x.columns:
        return pd.DataFrame()

    x = x.copy()

    x["QTL_GENE_EFFECTIVE"] = x.apply(
        effective_qtl_gene,
        axis=1,
    )

    if "LCLPP_MULTICAUSAL" in x.columns:
        x["LCLPP_MULTICAUSAL"] = safe_numeric(
            x["LCLPP_MULTICAUSAL"]
        )

    else:
        x["LCLPP_MULTICAUSAL"] = np.nan

    return x


def best_qtl_by_locus(qtl, qtl_type):
    if qtl.empty:
        return pd.DataFrame()

    q = qtl[
        qtl.get(
            "QTL_TYPE",
            pd.Series("", index=qtl.index),
        )
        .fillna("")
        .astype(str)
        .str.lower()
        ==
        qtl_type.lower()
    ].copy()

    if q.empty:
        return pd.DataFrame()

    q = q.sort_values(
        [
            "LOCUS_ID",
            "LCLPP_MULTICAUSAL",
        ],
        ascending=[
            True,
            False,
        ],
    )

    q = q.drop_duplicates(
        "LOCUS_ID",
        keep="first",
    )

    prefix = (
        "EQTL"
        if qtl_type.lower() == "eqtl"
        else
        "SQTL"
    )

    rename = {
        "QTL_GENE_EFFECTIVE":
            f"{prefix}_GENE",

        "TISSUE":
            f"{prefix}_TISSUE",

        "LCLPP_MULTICAUSAL":
            f"{prefix}_LCLPP",

        "TOP_SHARED_VARIANT":
            f"{prefix}_TOP_SHARED_VARIANT",

        "QTL_PHENOTYPE":
            f"{prefix}_PHENOTYPE",
    }

    keep = [
        "LOCUS_ID",
        *[
            c
            for c in rename
            if c in q.columns
        ],
    ]

    return q[
        keep
    ].rename(
        columns=rename
    )


# =============================================================================
# STEP13 OPEN TARGETS STATUS
# =============================================================================

def load_step13_status(paths):
    base = paths["S13"]

    files = [
        (
            "MATCHED",
            base / "matched_loci.tsv",
        ),
        (
            "GWAS2M_ONLY_COMPARABLE",
            base / "gwas2m_only_comparable.tsv",
        ),
        (
            "GWAS2M_ONLY_NO_OT_COVERAGE",
            base / "gwas2m_only_no_ot_coverage.tsv",
        ),
    ]

    rows = []

    for label, path in files:
        x = read_table(path)

        if x.empty:
            continue

        study_col = first_existing(
            x.columns,
            [
                "STUDY_ID",
            ],
        )

        locus_col = first_existing(
            x.columns,
            [
                "GWAS2M_LOCUS_ID",
            ],
        )

        if not study_col or not locus_col:
            continue

        for _, row in x.iterrows():
            rows.append(
                {
                    "STUDY_ID":
                        str(row[study_col]),

                    "LOCUS_ID":
                        str(row[locus_col]),

                    "OT_LOCUS_STATUS":
                        label,

                    "OT_STUDY_LOCUS_ID":
                        row.get(
                            "OT_STUDY_LOCUS_ID",
                            "",
                        ),

                    "OT_METHOD":
                        row.get(
                            "OT_FINEMAPPING_METHOD",
                            row.get(
                                "OT_METHODS",
                                "",
                            ),
                        ),

                    "OT_LEAD_VARIANT":
                        row.get(
                            "OT_LEAD_VARIANT",
                            row.get(
                                "OT_LEADS",
                                "",
                            ),
                        ),

                    "OT_MATCH_BASIS":
                        row.get(
                            "MATCH_BASIS",
                            row.get(
                                "BEST_MATCH_CLASS",
                                "",
                            ),
                        ),
                }
            )

    if not rows:
        return pd.DataFrame()

    return (
        pd.DataFrame(rows)
        .drop_duplicates(
            [
                "STUDY_ID",
                "LOCUS_ID",
            ],
            keep="first",
        )
    )


# =============================================================================
# OPTIONAL RESOURCES
# =============================================================================

def resource_candidates(base, names):
    out = []

    for name in names:
        out.extend(
            [
                base / name,
                base / f"{name}.tsv",
                base / f"{name}.tsv.gz",
            ]
        )

    return out


def first_existing_file(paths):
    for path in paths:
        if (
            path.exists()
            and
            path.is_file()
            and
            path.stat().st_size > 0
        ):
            return path.resolve()

    return None


def load_variant_resource(path, resource_name):
    x = read_table(path)

    if x.empty:
        return x

    if "VARIANT_KEY" not in x.columns:
        chr_col = first_existing(
            x.columns,
            ["CHR", "CHROM", "CHROMOSOME"],
        )

        pos_col = first_existing(
            x.columns,
            ["POS", "POSITION"],
        )

        ref_col = first_existing(
            x.columns,
            ["REF", "REFERENCE", "REFERENCE_ALLELE"],
        )

        alt_col = first_existing(
            x.columns,
            ["ALT", "ALTERNATE", "ALTERNATE_ALLELE"],
        )

        if all(
            [chr_col, pos_col, ref_col, alt_col]
        ):
            x["VARIANT_KEY"] = [
                canonical_variant_from_parts(c, p, r, a)
                for c, p, r, a
                in zip(
                    x[chr_col],
                    x[pos_col],
                    x[ref_col],
                    x[alt_col],
                )
            ]

        else:
            raise RuntimeError(
                f"{resource_name} resource needs VARIANT_KEY "
                "or CHR/POS/REF/ALT columns: "
                f"{path}"
            )

    x["VARIANT_KEY"] = x[
        "VARIANT_KEY"
    ].map(canonical_variant)

    x = x[
        x["VARIANT_KEY"].astype(str).str.len() > 0
    ].copy()

    return x.drop_duplicates(
        "VARIANT_KEY",
        keep="first",
    )


def load_gene_resource(path):
    x = read_table(path)

    if x.empty:
        return x

    gene_id_col = first_existing(
        x.columns,
        ["GENE_ID", "GENE", "ENSEMBL_GENE_ID"],
    )

    symbol_col = first_existing(
        x.columns,
        ["SYMBOL", "GENE_SYMBOL"],
    )

    if gene_id_col:
        x["_GENE_ID_BASE"] = x[
            gene_id_col
        ].map(gene_base)

    else:
        x["_GENE_ID_BASE"] = ""

    if symbol_col:
        x["_GENE_SYMBOL"] = x[
            symbol_col
        ].fillna("").astype(str)

    else:
        x["_GENE_SYMBOL"] = ""

    return x


def load_optional_resources(paths, args):
    base = paths["RESOURCES"]

    explicit = {
        "CLINVAR":
            Path(args.clinvar).resolve()
            if args.clinvar
            else None,

        "ALPHAMISSENSE":
            Path(args.alphamissense).resolve()
            if args.alphamissense
            else None,

        "CADD":
            Path(args.cadd).resolve()
            if args.cadd
            else None,

        "GENE_CONSTRAINT":
            Path(args.gene_constraint).resolve()
            if args.gene_constraint
            else None,

        "MENDELIAN":
            Path(args.mendelian_resource).resolve()
            if args.mendelian_resource
            else None,
    }

    auto = {
        "CLINVAR":
            first_existing_file(
                resource_candidates(
                    base,
                    ["clinvar"],
                )
            ),

        "ALPHAMISSENSE":
            first_existing_file(
                resource_candidates(
                    base,
                    ["alphamissense"],
                )
            ),

        "CADD":
            first_existing_file(
                resource_candidates(
                    base,
                    ["cadd"],
                )
            ),

        "GENE_CONSTRAINT":
            first_existing_file(
                resource_candidates(
                    base,
                    [
                        "gene_constraint",
                        "gnomad_gene_constraint",
                    ],
                )
            ),

        "MENDELIAN":
            first_existing_file(
                resource_candidates(
                    base,
                    [
                        "mendelian_gene_disease",
                        "gene_disease",
                    ],
                )
            ),
    }

    status = []

    resources = {}

    for name in explicit:
        path = explicit[name] or auto[name]

        available = bool(
            path
            and
            path.exists()
            and
            path.stat().st_size > 0
        )

        status.append(
            {
                "RESOURCE":
                    name,

                "AVAILABLE":
                    available,

                "PATH":
                    str(path)
                    if path
                    else "",

                "INTERPRETATION":
                    (
                        "USED"
                        if available
                        else
                        "NOT_AVAILABLE_NOT_NEGATIVE_EVIDENCE"
                    ),
            }
        )

        if not available:
            resources[name] = pd.DataFrame()
            continue

        if name in {
            "CLINVAR",
            "ALPHAMISSENSE",
            "CADD",
        }:
            resources[name] = load_variant_resource(
                path,
                name,
            )

        else:
            resources[name] = load_gene_resource(
                path
            )

    return resources, pd.DataFrame(status)


# =============================================================================
# CONSEQUENCE INTERPRETATION
# =============================================================================

PTV_TERMS = {
    "transcript_ablation",
    "splice_acceptor_variant",
    "splice_donor_variant",
    "stop_gained",
    "frameshift_variant",
    "start_lost",
}

MISSENSE_TERMS = {
    "missense_variant",
    "protein_altering_variant",
    "inframe_insertion",
    "inframe_deletion",
}

SYNONYMOUS_TERMS = {
    "synonymous_variant",
    "start_retained_variant",
    "stop_retained_variant",
}

SPLICE_TERMS = {
    "splice_acceptor_variant",
    "splice_donor_variant",
    "splice_region_variant",
    "splice_donor_5th_base_variant",
    "splice_donor_region_variant",
    "splice_polypyrimidine_tract_variant",
}

UTR_TERMS = {
    "5_prime_utr_variant",
    "3_prime_utr_variant",
}

REGULATORY_TERMS = {
    "regulatory_region_variant",
    "TF_binding_site_variant",
    "upstream_gene_variant",
    "downstream_gene_variant",
}

NONCODING_RNA_BIOTYPE_TOKENS = {
    "lncrna",
    "lincRNA",
    "antisense",
    "processed_transcript",
    "miRNA",
    "snRNA",
    "snoRNA",
    "rRNA",
    "misc_RNA",
    "non_coding",
}


def consequence_tokens(row):
    values = []

    for col in [
        "Consequence",
        "ALL_CONSEQUENCES",
    ]:
        value = row.get(col)

        if value is None:
            continue

        try:
            if pd.isna(value):
                continue
        except Exception:
            pass

        text = str(value)

        for token in re.split(r"[,;&]", text):
            token = token.strip().lower()

            if token:
                values.append(token)

    return set(values)


def classify_variant_context(row):
    terms = consequence_tokens(row)

    biotype = str(
        row.get("BIOTYPE", "")
    ).lower()

    functional = str(
        row.get(
            "FUNCTIONAL_CATEGORY",
            "",
        )
    ).upper()

    if terms & PTV_TERMS:
        return "CODING_PTV_OR_CANONICAL_SPLICE"

    if terms & MISSENSE_TERMS:
        return "CODING_MISSENSE_OR_PROTEIN_ALTERING"

    if terms & SYNONYMOUS_TERMS:
        return "CODING_SYNONYMOUS"

    if terms & SPLICE_TERMS:
        return "SPLICE_REGION"

    if terms & UTR_TERMS:
        return "UTR"

    if (
        functional == "NONCODING_RNA"
        or
        any(
            token.lower() in biotype
            for token in NONCODING_RNA_BIOTYPE_TOKENS
        )
    ):
        return "NONCODING_RNA"

    if (
        functional == "REGULATORY"
        or
        terms & {
            x.lower()
            for x in REGULATORY_TERMS
        }
    ):
        return "REGULATORY"

    if "intron_variant" in terms:
        return "INTRONIC"

    if "intergenic_variant" in terms:
        return "INTERGENIC"

    if functional == "CODING":
        return "CODING_OTHER"

    if functional == "SPLICING":
        return "SPLICING_OTHER"

    return "OTHER_OR_UNRESOLVED"


def protein_interpretation(row):
    context = row.get(
        "VARIANT_CONTEXT",
        "",
    )

    consequence = str(
        row.get(
            "Consequence",
            "",
        )
    )

    hgvsp = str(
        row.get(
            "HGVSp",
            "",
        )
    )

    aa = str(
        row.get(
            "Amino_acids",
            "",
        )
    )

    pos = str(
        row.get(
            "Protein_position",
            "",
        )
    )

    sift = str(
        row.get(
            "SIFT",
            "",
        )
    )

    polyphen = str(
        row.get(
            "PolyPhen",
            "",
        )
    )

    domain = str(
        row.get(
            "DOMAINS",
            "",
        )
    )

    parts = []

    if context == "CODING_PTV_OR_CANONICAL_SPLICE":
        parts.append(
            "protein-truncating/canonical-splice candidate"
        )

    elif context == "CODING_MISSENSE_OR_PROTEIN_ALTERING":
        parts.append(
            "protein-sequence-altering candidate"
        )

    elif context == "CODING_SYNONYMOUS":
        parts.append(
            "synonymous coding variant"
        )

    elif context.startswith("CODING"):
        parts.append(
            "coding variant"
        )

    else:
        return ""

    if consequence and consequence.lower() != "nan":
        parts.append(
            f"VEP={consequence}"
        )

    if hgvsp and hgvsp.lower() != "nan":
        parts.append(
            f"HGVSp={hgvsp}"
        )

    if aa and aa.lower() != "nan":
        parts.append(
            f"AA={aa}"
        )

    if pos and pos.lower() != "nan":
        parts.append(
            f"protein_position={pos}"
        )

    if sift and sift.lower() != "nan":
        parts.append(
            f"SIFT={sift}"
        )

    if polyphen and polyphen.lower() != "nan":
        parts.append(
            f"PolyPhen={polyphen}"
        )

    if domain and domain.lower() != "nan":
        parts.append(
            f"domain={domain}"
        )

    return " | ".join(parts)


# =============================================================================
# OPTIONAL RESOURCE MERGES
# =============================================================================

def rename_resource_columns(
    x,
    resource,
):
    if x.empty:
        return x

    x = x.copy()

    renames = {}

    if resource == "CLINVAR":
        mappings = {
            "CLINVAR_SIGNIFICANCE":
                [
                    "CLINVAR_SIGNIFICANCE",
                    "CLNSIG",
                    "SIGNIFICANCE",
                ],

            "CLINVAR_CONDITION":
                [
                    "CLINVAR_CONDITION",
                    "CLNDN",
                    "CONDITION",
                ],

            "CLINVAR_REVIEW_STATUS":
                [
                    "CLINVAR_REVIEW_STATUS",
                    "CLNREVSTAT",
                    "REVIEW_STATUS",
                ],
        }

    elif resource == "ALPHAMISSENSE":
        mappings = {
            "ALPHAMISSENSE_SCORE":
                [
                    "ALPHAMISSENSE_SCORE",
                    "AM_SCORE",
                    "SCORE",
                ],

            "ALPHAMISSENSE_CLASS":
                [
                    "ALPHAMISSENSE_CLASS",
                    "AM_CLASS",
                    "CLASS",
                ],
        }

    elif resource == "CADD":
        mappings = {
            "CADD_PHRED":
                [
                    "CADD_PHRED",
                    "PHRED",
                    "CADD",
                ],
        }

    else:
        mappings = {}

    for target, candidates in mappings.items():
        source = first_existing(
            x.columns,
            candidates,
        )

        if source:
            renames[source] = target

    return x.rename(
        columns=renames
    )


def merge_optional_variant_resources(df, resources):
    out = df.copy()

    for resource in [
        "CLINVAR",
        "ALPHAMISSENSE",
        "CADD",
    ]:
        x = resources.get(
            resource,
            pd.DataFrame(),
        )

        if x.empty:
            continue

        x = rename_resource_columns(
            x,
            resource,
        )

        keep = [
            c
            for c in x.columns
            if (
                c == "VARIANT_KEY"
                or
                c.startswith(
                    resource
                )
                or
                (
                    resource == "CADD"
                    and c == "CADD_PHRED"
                )
            )
        ]

        x = x[
            keep
        ].drop_duplicates(
            "VARIANT_KEY",
            keep="first",
        )

        out = out.merge(
            x,
            on="VARIANT_KEY",
            how="left",
            validate="many_to_one",
        )

    return out


def choose_primary_gene(row):
    for col in [
        "SYMBOL",
        "Gene",
        "EQTL_GENE",
        "SQTL_GENE",
        "PANGOLIN_GENE",
        "SPLICEAI_GENE",
    ]:
        value = row.get(col)

        if value is None:
            continue

        try:
            if pd.isna(value):
                continue
        except Exception:
            pass

        x = str(value).strip()

        if x and x.lower() not in {
            "nan", "none", "."
        }:
            return gene_base(x)

    return ""


def merge_gene_resources(df, resources):
    out = df.copy()

    out["PRIMARY_GENE"] = out.apply(
        choose_primary_gene,
        axis=1,
    )

    # Constraint
    constraint = resources.get(
        "GENE_CONSTRAINT",
        pd.DataFrame(),
    )

    if not constraint.empty:
        loeuf = first_existing(
            constraint.columns,
            [
                "LOEUF",
                "oe_lof_upper",
            ],
        )

        pli = first_existing(
            constraint.columns,
            [
                "PLI",
                "pLI",
            ],
        )

        rows = []

        for _, row in constraint.iterrows():
            key = (
                gene_base(
                    row.get(
                        "_GENE_ID_BASE",
                        "",
                    )
                )
                or
                str(
                    row.get(
                        "_GENE_SYMBOL",
                        "",
                    )
                ).strip()
            )

            if not key:
                continue

            rows.append(
                {
                    "PRIMARY_GENE":
                        key,

                    "GNOMAD_LOEUF":
                        row.get(
                            loeuf,
                            np.nan,
                        )
                        if loeuf
                        else
                        np.nan,

                    "GNOMAD_PLI":
                        row.get(
                            pli,
                            np.nan,
                        )
                        if pli
                        else
                        np.nan,
                }
            )

        if rows:
            out = out.merge(
                pd.DataFrame(rows).drop_duplicates(
                    "PRIMARY_GENE",
                    keep="first",
                ),
                on="PRIMARY_GENE",
                how="left",
                validate="many_to_one",
            )

    # Mendelian
    mendelian = resources.get(
        "MENDELIAN",
        pd.DataFrame(),
    )

    if not mendelian.empty:
        disease_col = first_existing(
            mendelian.columns,
            [
                "MENDELIAN_DISEASE",
                "DISEASE",
                "CONDITION",
            ],
        )

        source_col = first_existing(
            mendelian.columns,
            [
                "MENDELIAN_SOURCE",
                "SOURCE",
            ],
        )

        evidence_col = first_existing(
            mendelian.columns,
            [
                "MENDELIAN_EVIDENCE",
                "EVIDENCE",
            ],
        )

        rows = []

        for _, row in mendelian.iterrows():
            key = (
                gene_base(
                    row.get(
                        "_GENE_ID_BASE",
                        "",
                    )
                )
                or
                str(
                    row.get(
                        "_GENE_SYMBOL",
                        "",
                    )
                ).strip()
            )

            if not key:
                continue

            rows.append(
                {
                    "PRIMARY_GENE":
                        key,

                    "MENDELIAN_DISEASE":
                        row.get(
                            disease_col,
                            "",
                        )
                        if disease_col
                        else "",

                    "MENDELIAN_SOURCE":
                        row.get(
                            source_col,
                            "",
                        )
                        if source_col
                        else "",

                    "MENDELIAN_EVIDENCE":
                        row.get(
                            evidence_col,
                            "",
                        )
                        if evidence_col
                        else "",
                }
            )

        if rows:
            m = pd.DataFrame(rows)

            m = (
                m.groupby(
                    "PRIMARY_GENE",
                    as_index=False,
                )
                .agg(
                    MENDELIAN_DISEASE=(
                        "MENDELIAN_DISEASE",
                        join_unique,
                    ),
                    MENDELIAN_SOURCE=(
                        "MENDELIAN_SOURCE",
                        join_unique,
                    ),
                    MENDELIAN_EVIDENCE=(
                        "MENDELIAN_EVIDENCE",
                        join_unique,
                    ),
                )
            )

            out = out.merge(
                m,
                on="PRIMARY_GENE",
                how="left",
                validate="many_to_one",
            )

    return out


# =============================================================================
# MECHANISM CLASSIFICATION
# =============================================================================

def classify_mechanism(row, args):
    context = str(
        row.get(
            "VARIANT_CONTEXT",
            "",
        )
    )

    eqtl = row.get(
        "EQTL_LCLPP",
        np.nan,
    )

    sqtl = row.get(
        "SQTL_LCLPP",
        np.nan,
    )

    spliceai = row.get(
        "SPLICEAI_MAX_DS",
        np.nan,
    )

    pang_top5 = boolish(
        row.get(
            "PANGOLIN_TOP_5PCT",
            False,
        )
    )

    try:
        eqtl_support = (
            pd.notna(eqtl)
            and float(eqtl)
            >= args.eqtl_screen
        )

    except Exception:
        eqtl_support = False

    try:
        sqtl_support = (
            pd.notna(sqtl)
            and float(sqtl)
            >= args.sqtl_screen
        )

    except Exception:
        sqtl_support = False

    try:
        spliceai_support = (
            pd.notna(spliceai)
            and float(spliceai)
            >= args.spliceai_support
        )

    except Exception:
        spliceai_support = False

    canonical_splice = (
        "splice_acceptor_variant"
        in consequence_tokens(row)
        or
        "splice_donor_variant"
        in consequence_tokens(row)
    )

    ptv = (
        context
        ==
        "CODING_PTV_OR_CANONICAL_SPLICE"
        and
        not canonical_splice
    )

    missense = (
        context
        ==
        "CODING_MISSENSE_OR_PROTEIN_ALTERING"
    )

    expression = bool(
        eqtl_support
    )

    splicing = bool(
        canonical_splice
        or
        sqtl_support
        or
        spliceai_support
        or
        pang_top5
    )

    coding = bool(
        context.startswith(
            "CODING"
        )
    )

    mechanism_axes = []

    if ptv:
        mechanism_axes.append(
            "PROTEIN_TRUNCATION"
        )

    if missense:
        mechanism_axes.append(
            "PROTEIN_SEQUENCE"
        )

    if expression:
        mechanism_axes.append(
            "EXPRESSION"
        )

    if splicing:
        mechanism_axes.append(
            "SPLICING"
        )

    if (
        context
        in {
            "REGULATORY",
            "INTRONIC",
            "INTERGENIC",
            "UTR",
        }
        and
        expression
    ):
        mechanism_axes.append(
            "NONCODING_REGULATORY"
        )

    if context == "NONCODING_RNA":
        mechanism_axes.append(
            "NONCODING_RNA"
        )

    # Remove duplicates.
    mechanism_axes = list(
        dict.fromkeys(
            mechanism_axes
        )
    )

    if len(mechanism_axes) >= 2:
        mechanism = "MULTI_MECHANISM"

    elif ptv:
        mechanism = "CODING_PTV_CANDIDATE"

    elif missense:
        mechanism = "CODING_MISSENSE"

    elif canonical_splice:
        mechanism = "CANONICAL_SPLICE"

    elif splicing:
        mechanism = "SPLICING_MEDIATED"

    elif expression and not coding:
        mechanism = "EXPRESSION_MEDIATED_NONCODING"

    elif expression:
        mechanism = "EXPRESSION_MEDIATED"

    elif context == "NONCODING_RNA":
        mechanism = "NONCODING_RNA"

    elif context in {
        "REGULATORY",
        "INTRONIC",
        "INTERGENIC",
        "UTR",
    }:
        mechanism = "UNRESOLVED_NONCODING"

    elif context == "CODING_SYNONYMOUS":
        mechanism = "CODING_SYNONYMOUS_UNRESOLVED"

    elif coding:
        mechanism = "CODING_OTHER"

    else:
        mechanism = "UNRESOLVED"

    return pd.Series(
        {
            "MECHANISM_CLASS":
                mechanism,

            "MECHANISM_AXES":
                ";".join(
                    mechanism_axes
                ),

            "HAS_EXPRESSION_SUPPORT":
                expression,

            "HAS_SPLICING_SUPPORT":
                splicing,

            "HAS_PROTEIN_SEQUENCE_SUPPORT":
                (
                    ptv
                    or
                    missense
                ),
        }
    )


def followup_requirements(row, resource_status):
    available = {
        str(r["RESOURCE"]):
            bool(r["AVAILABLE"])
        for _, r in resource_status.iterrows()
    }

    needs = []

    context = str(
        row.get(
            "VARIANT_CONTEXT",
            "",
        )
    )

    if context == "CODING_PTV_OR_CANONICAL_SPLICE":
        needs.append(
            "LOFTEE_HIGH_CONFIDENCE_LOF"
        )

    if (
        context
        ==
        "CODING_MISSENSE_OR_PROTEIN_ALTERING"
        and
        not available.get(
            "ALPHAMISSENSE",
            False,
        )
    ):
        needs.append(
            "ALPHAMISSENSE"
        )

    if (
        context.startswith(
            "CODING"
        )
        and
        not available.get(
            "CLINVAR",
            False,
        )
    ):
        needs.append(
            "CLINVAR"
        )

    if (
        context.startswith(
            "CODING"
        )
        and
        not available.get(
            "CADD",
            False,
        )
    ):
        needs.append(
            "CADD"
        )

    if (
        row.get(
            "MECHANISM_CLASS",
            ""
        )
        in {
            "EXPRESSION_MEDIATED",
            "EXPRESSION_MEDIATED_NONCODING",
            "SPLICING_MEDIATED",
            "MULTI_MECHANISM",
        }
    ):
        needs.append(
            "FORMAL_COLOCALISATION_VALIDATION"
        )

    if not available.get(
        "MENDELIAN",
        False,
    ):
        needs.append(
            "MENDELIAN_GENE_DISEASE_RESOURCE"
        )

    if not available.get(
        "GENE_CONSTRAINT",
        False,
    ):
        needs.append(
            "GNOMAD_GENE_CONSTRAINT"
        )

    return ";".join(
        dict.fromkeys(
            needs
        )
    )


# =============================================================================
# ONE STUDY
# =============================================================================

def process_study(
    paths,
    study,
    resources,
    resource_status,
    ot_status,
    args,
):
    vep = load_step07(
        paths,
        study,
    )

    if vep.empty:
        return pd.DataFrame()

    splice = load_step10(
        paths,
        study,
    )

    qtl = load_step11(
        paths,
        study,
    )

    eqtl = best_qtl_by_locus(
        qtl,
        "eQTL",
    )

    sqtl = best_qtl_by_locus(
        qtl,
        "sQTL",
    )

    x = vep.copy()

    x["STUDY_ID"] = study

    if not splice.empty:
        x = x.merge(
            splice,
            on="VARIANT_KEY",
            how="left",
            suffixes=(
                "",
                "_STEP10",
            ),
            validate="one_to_one",
        )

    if not eqtl.empty:
        x = x.merge(
            eqtl,
            on="LOCUS_ID",
            how="left",
            validate="many_to_one",
        )

    if not sqtl.empty:
        x = x.merge(
            sqtl,
            on="LOCUS_ID",
            how="left",
            validate="many_to_one",
        )

    if not ot_status.empty:
        local_ot = ot_status[
            ot_status[
                "STUDY_ID"
            ].astype(str)
            ==
            study
        ].copy()

        if not local_ot.empty:
            x = x.merge(
                local_ot.drop(
                    columns=[
                        "STUDY_ID",
                    ],
                    errors="ignore",
                ),
                on="LOCUS_ID",
                how="left",
                validate="many_to_one",
            )

    x = merge_optional_variant_resources(
        x,
        resources,
    )

    x["VARIANT_CONTEXT"] = x.apply(
        classify_variant_context,
        axis=1,
    )

    x["PROTEIN_INTERPRETATION"] = x.apply(
        protein_interpretation,
        axis=1,
    )

    # Exact top-shared variant matching.
    for prefix in [
        "EQTL",
        "SQTL",
    ]:
        col = (
            f"{prefix}_TOP_SHARED_VARIANT"
        )

        if col in x.columns:
            x[
                f"{prefix}_TOP_VARIANT_MATCH"
            ] = [
                canonical_variant(
                    v
                )
                ==
                canonical_variant(
                    q
                )
                and
                bool(
                    canonical_variant(
                        v
                    )
                )
                for v, q
                in zip(
                    x[
                        "VARIANT_KEY"
                    ],
                    x[
                        col
                    ],
                )
            ]

        else:
            x[
                f"{prefix}_TOP_VARIANT_MATCH"
            ] = False

    classification = x.apply(
        classify_mechanism,
        axis=1,
        args=args,
    )

    x = pd.concat(
        [
            x.reset_index(
                drop=True
            ),
            classification.reset_index(
                drop=True
            ),
        ],
        axis=1,
    )

    x = merge_gene_resources(
        x,
        resources,
    )

    x["FOLLOWUP_REQUIREMENTS"] = x.apply(
        lambda row:
            followup_requirements(
                row,
                resource_status,
            ),
        axis=1,
    )

    # Explicit evidence presence; absence of resource != negative evidence.
    x["CLINVAR_AVAILABLE_FOR_VARIANT"] = (
        x.get(
            "CLINVAR_SIGNIFICANCE",
            pd.Series(
                np.nan,
                index=x.index,
            ),
        )
        .notna()
    )

    x["ALPHAMISSENSE_AVAILABLE_FOR_VARIANT"] = (
        x.get(
            "ALPHAMISSENSE_SCORE",
            pd.Series(
                np.nan,
                index=x.index,
            ),
        )
        .notna()
    )

    x["CADD_AVAILABLE_FOR_VARIANT"] = (
        x.get(
            "CADD_PHRED",
            pd.Series(
                np.nan,
                index=x.index,
            ),
        )
        .notna()
    )

    # A descriptive evidence count only, NOT a causal score.
    evidence_columns = [
        "IN_95_CREDIBLE_SET",
        "HAS_EXPRESSION_SUPPORT",
        "HAS_SPLICING_SUPPORT",
        "HAS_PROTEIN_SEQUENCE_SUPPORT",
        "EQTL_TOP_VARIANT_MATCH",
        "SQTL_TOP_VARIANT_MATCH",
        "CLINVAR_AVAILABLE_FOR_VARIANT",
        "ALPHAMISSENSE_AVAILABLE_FOR_VARIANT",
        "CADD_AVAILABLE_FOR_VARIANT",
    ]

    x["N_DOCUMENTED_EVIDENCE_FLAGS"] = 0

    for col in evidence_columns:
        if col in x.columns:
            x[
                "N_DOCUMENTED_EVIDENCE_FLAGS"
            ] += x[
                col
            ].map(
                boolish
            ).astype(int)

    # Sort strongest fine-mapping first.
    x = x.sort_values(
        [
            "LOCUS_ID",
            "PIP",
        ],
        ascending=[
            True,
            False,
        ],
        kind="stable",
    )

    out_dir = (
        paths["OUT"]
        /
        study
    )

    out_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    x.to_csv(
        out_dir
        /
        f"{study}_mechanism_variants.tsv.gz",

        sep="\t",

        index=False,

        compression="gzip",
    )

    return x


# =============================================================================
# SUMMARIES
# =============================================================================

def make_locus_summary(all_variants):
    if all_variants.empty:
        return pd.DataFrame()

    rows = []

    for (
        study,
        locus,
    ), g in all_variants.groupby(
        [
            "STUDY_ID",
            "LOCUS_ID",
        ],
        sort=False,
        dropna=False,
    ):
        g = g.sort_values(
            "PIP",
            ascending=False,
        )

        top = g.iloc[0]

        best_eqtl = safe_numeric(
            g.get(
                "EQTL_LCLPP",
                pd.Series(
                    np.nan,
                    index=g.index,
                ),
            )
        ).max()

        best_sqtl = safe_numeric(
            g.get(
                "SQTL_LCLPP",
                pd.Series(
                    np.nan,
                    index=g.index,
                ),
            )
        ).max()

        rows.append(
            {
                "STUDY_ID":
                    study,

                "LOCUS_ID":
                    locus,

                "N_VARIANTS":
                    len(g),

                "N_95CS":
                    int(
                        g[
                            "IN_95_CREDIBLE_SET"
                        ].map(
                            boolish
                        ).sum()
                    ),

                "TOP_VARIANT":
                    top[
                        "VARIANT_KEY"
                    ],

                "TOP_PIP":
                    top[
                        "PIP"
                    ],

                "TOP_CONTEXT":
                    top[
                        "VARIANT_CONTEXT"
                    ],

                "TOP_MECHANISM":
                    top[
                        "MECHANISM_CLASS"
                    ],

                "TOP_GENE":
                    top.get(
                        "PRIMARY_GENE",
                        "",
                    ),

                "ALL_MECHANISM_CLASSES":
                    join_unique(
                        g[
                            "MECHANISM_CLASS"
                        ]
                    ),

                "N_CODING_PTV":
                    int(
                        (
                            g[
                                "MECHANISM_CLASS"
                            ]
                            ==
                            "CODING_PTV_CANDIDATE"
                        ).sum()
                    ),

                "N_CODING_MISSENSE":
                    int(
                        (
                            g[
                                "MECHANISM_CLASS"
                            ]
                            ==
                            "CODING_MISSENSE"
                        ).sum()
                    ),

                "N_EXPRESSION_SUPPORTED":
                    int(
                        g[
                            "HAS_EXPRESSION_SUPPORT"
                        ].map(
                            boolish
                        ).sum()
                    ),

                "N_SPLICING_SUPPORTED":
                    int(
                        g[
                            "HAS_SPLICING_SUPPORT"
                        ].map(
                            boolish
                        ).sum()
                    ),

                "BEST_EQTL_LCLPP":
                    best_eqtl,

                "BEST_SQTL_LCLPP":
                    best_sqtl,

                "EQTL_GENE":
                    top.get(
                        "EQTL_GENE",
                        "",
                    ),

                "EQTL_TISSUE":
                    top.get(
                        "EQTL_TISSUE",
                        "",
                    ),

                "SQTL_GENE":
                    top.get(
                        "SQTL_GENE",
                        "",
                    ),

                "SQTL_TISSUE":
                    top.get(
                        "SQTL_TISSUE",
                        "",
                    ),

                "OT_LOCUS_STATUS":
                    top.get(
                        "OT_LOCUS_STATUS",
                        "",
                    ),

                "OT_METHOD":
                    top.get(
                        "OT_METHOD",
                        "",
                    ),

                "OT_LEAD_VARIANT":
                    top.get(
                        "OT_LEAD_VARIANT",
                        "",
                    ),

                "OT_MATCH_BASIS":
                    top.get(
                        "OT_MATCH_BASIS",
                        "",
                    ),
            }
        )

    return pd.DataFrame(
        rows
    ).sort_values(
        [
            "STUDY_ID",
            "TOP_PIP",
        ],
        ascending=[
            True,
            False,
        ],
    )


def make_study_summary(all_variants):
    if all_variants.empty:
        return pd.DataFrame()

    rows = []

    for study, g in all_variants.groupby(
        "STUDY_ID",
        sort=True,
    ):
        rows.append(
            {
                "STUDY_ID":
                    study,

                "N_VARIANTS":
                    len(g),

                "N_LOCI":
                    g[
                        "LOCUS_ID"
                    ].nunique(),

                "N_95CS":
                    int(
                        g[
                            "IN_95_CREDIBLE_SET"
                        ].map(
                            boolish
                        ).sum()
                    ),

                "N_CODING":
                    int(
                        g[
                            "VARIANT_CONTEXT"
                        ].astype(str).str.startswith(
                            "CODING"
                        ).sum()
                    ),

                "N_PTV_CANDIDATE":
                    int(
                        (
                            g[
                                "MECHANISM_CLASS"
                            ]
                            ==
                            "CODING_PTV_CANDIDATE"
                        ).sum()
                    ),

                "N_MISSENSE":
                    int(
                        (
                            g[
                                "MECHANISM_CLASS"
                            ]
                            ==
                            "CODING_MISSENSE"
                        ).sum()
                    ),

                "N_NONCODING":
                    int(
                        (
                            ~g[
                                "VARIANT_CONTEXT"
                            ].astype(str).str.startswith(
                                "CODING"
                            )
                        ).sum()
                    ),

                "N_EXPRESSION_MEDIATED":
                    int(
                        g[
                            "MECHANISM_CLASS"
                        ].astype(str).str.contains(
                            "EXPRESSION",
                            regex=False,
                        ).sum()
                    ),

                "N_SPLICING_MEDIATED":
                    int(
                        g[
                            "HAS_SPLICING_SUPPORT"
                        ].map(
                            boolish
                        ).sum()
                    ),

                "N_MULTI_MECHANISM":
                    int(
                        (
                            g[
                                "MECHANISM_CLASS"
                            ]
                            ==
                            "MULTI_MECHANISM"
                        ).sum()
                    ),

                "N_UNRESOLVED":
                    int(
                        g[
                            "MECHANISM_CLASS"
                        ].astype(str).str.contains(
                            "UNRESOLVED",
                            regex=False,
                        ).sum()
                    ),
            }
        )

    return pd.DataFrame(
        rows
    )


def make_top_candidates(all_variants):
    if all_variants.empty:
        return pd.DataFrame()

    x = all_variants.copy()

    mechanism_priority = {
        "MULTI_MECHANISM": 1,
        "CODING_PTV_CANDIDATE": 2,
        "CANONICAL_SPLICE": 3,
        "CODING_MISSENSE": 4,
        "SPLICING_MEDIATED": 5,
        "EXPRESSION_MEDIATED_NONCODING": 6,
        "EXPRESSION_MEDIATED": 7,
        "NONCODING_RNA": 8,
        "CODING_OTHER": 9,
        "UNRESOLVED_NONCODING": 10,
        "UNRESOLVED": 11,
    }

    x["_MECH_PRIORITY"] = x[
        "MECHANISM_CLASS"
    ].map(
        mechanism_priority
    ).fillna(
        99
    )

    x = x.sort_values(
        [
            "_MECH_PRIORITY",
            "PIP",
            "N_DOCUMENTED_EVIDENCE_FLAGS",
        ],
        ascending=[
            True,
            False,
            False,
        ],
    )

    x = x.drop_duplicates(
        [
            "STUDY_ID",
            "LOCUS_ID",
        ],
        keep="first",
    )

    return x.drop(
        columns=[
            "_MECH_PRIORITY",
        ],
        errors="ignore",
    )


# =============================================================================
# MAIN
# =============================================================================

def arguments():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--phenotype",
        required=True,
    )

    parser.add_argument(
        "--ancestry",
        required=True,
    )

    parser.add_argument(
        "--study",
        default=None,
    )

    parser.add_argument(
        "--eqtl-screen",
        type=float,
        default=DEFAULT_EQTL_SCREEN,
    )

    parser.add_argument(
        "--sqtl-screen",
        type=float,
        default=DEFAULT_SQTL_SCREEN,
    )

    parser.add_argument(
        "--spliceai-support",
        type=float,
        default=DEFAULT_SPLICEAI_SUPPORT,
    )

    parser.add_argument(
        "--clinvar",
        default=None,
    )

    parser.add_argument(
        "--alphamissense",
        default=None,
    )

    parser.add_argument(
        "--cadd",
        default=None,
    )

    parser.add_argument(
        "--gene-constraint",
        default=None,
    )

    parser.add_argument(
        "--mendelian-resource",
        default=None,
    )

    parser.add_argument(
        "--max-print",
        type=int,
        default=50,
    )

    return parser.parse_args()


def main():
    args = arguments()

    root = Path.cwd().resolve()

    ancestry_code, ancestry_label = ancestry_info(
        args.ancestry
    )

    paths = make_paths(
        root,
        args.phenotype,
        ancestry_label,
    )

    paths["OUT"].mkdir(
        parents=True,
        exist_ok=True,
    )

    section(
        "GWAS2m STEP14 - LOCUS-TO-MECHANISM INTERPRETATION"
    )

    print(
        f"Version      : {VERSION}"
    )

    print(
        f"Root         : {root}"
    )

    print(
        f"Phenotype    : {args.phenotype}"
    )

    print(
        f"Ancestry     : {ancestry_label} ({ancestry_code})"
    )

    print(
        f"eQTL screen  : {args.eqtl_screen}"
    )

    print(
        f"sQTL screen  : {args.sqtl_screen}"
    )

    print(
        f"SpliceAI     : >= {args.spliceai_support}"
    )

    print(
        f"Output       : {paths['OUT']}"
    )

    studies = discover_studies(
        paths
    )

    if args.study:
        studies = [
            s
            for s in studies
            if s == args.study
        ]

    if not studies:
        raise SystemExit(
            "No studies found for Step14."
        )

    resources, resource_status = load_optional_resources(
        paths,
        args,
    )

    resource_status.to_csv(
        paths["OUT"]
        /
        "mechanism_resource_status.tsv",

        sep="\t",

        index=False,
    )

    show(
        resource_status,
        "OPTIONAL MECHANISM RESOURCE STATUS",
        args.max_print,
    )

    ot_status = load_step13_status(
        paths
    )

    all_frames = []

    processing = []

    for study in studies:
        try:
            x = process_study(
                paths,
                study,
                resources,
                resource_status,
                ot_status,
                args,
            )

            if x.empty:
                processing.append(
                    {
                        "STUDY_ID":
                            study,

                        "STATUS":
                            "NO_STEP07_VARIANTS",

                        "N_VARIANTS":
                            0,
                    }
                )

                continue

            all_frames.append(
                x
            )

            processing.append(
                {
                    "STUDY_ID":
                        study,

                    "STATUS":
                        "COMPLETE",

                    "N_VARIANTS":
                        len(x),

                    "N_LOCI":
                        x[
                            "LOCUS_ID"
                        ].nunique(),
                }
            )

            print(
                f"[Step14] {study}: "
                f"{len(x):,} variants / "
                f"{x['LOCUS_ID'].nunique():,} loci"
            )

        except Exception as error:
            processing.append(
                {
                    "STUDY_ID":
                        study,

                    "STATUS":
                        "FAILED",

                    "ERROR":
                        f"{type(error).__name__}: {error}",
                }
            )

            print(
                f"[WARN] {study}: "
                f"{type(error).__name__}: {error}"
            )

    processing_df = pd.DataFrame(
        processing
    )

    processing_df.to_csv(
        paths["OUT"]
        /
        "mechanism_processing_status.tsv",

        sep="\t",

        index=False,
    )

    if not all_frames:
        raise RuntimeError(
            "Step14 produced no usable study outputs. "
            "Inspect mechanism_processing_status.tsv."
        )

    all_variants = pd.concat(
        all_frames,
        ignore_index=True,
        sort=False,
    )

    locus_summary = make_locus_summary(
        all_variants
    )

    study_summary = make_study_summary(
        all_variants
    )

    top_candidates = make_top_candidates(
        all_variants
    )

    coding = all_variants[
        all_variants[
            "VARIANT_CONTEXT"
        ].astype(str).str.startswith(
            "CODING"
        )
        |
        (
            all_variants[
                "VARIANT_CONTEXT"
            ]
            ==
            "SPLICE_REGION"
        )
    ].copy()

    noncoding = all_variants[
        ~all_variants.index.isin(
            coding.index
        )
    ].copy()

    unresolved = all_variants[
        all_variants[
            "MECHANISM_CLASS"
        ].astype(str).str.contains(
            "UNRESOLVED",
            regex=False,
        )
    ].copy()

    all_variants.to_csv(
        paths["OUT"]
        /
        "all_variant_mechanisms.tsv.gz",

        sep="\t",

        index=False,

        compression="gzip",
    )

    coding.to_csv(
        paths["OUT"]
        /
        "coding_variant_mechanisms.tsv",

        sep="\t",

        index=False,
    )

    noncoding.to_csv(
        paths["OUT"]
        /
        "noncoding_variant_mechanisms.tsv",

        sep="\t",

        index=False,
    )

    unresolved.to_csv(
        paths["OUT"]
        /
        "unresolved_variant_mechanisms.tsv",

        sep="\t",

        index=False,
    )

    locus_summary.to_csv(
        paths["OUT"]
        /
        "locus_mechanism_summary.tsv",

        sep="\t",

        index=False,
    )

    study_summary.to_csv(
        paths["OUT"]
        /
        "study_mechanism_summary.tsv",

        sep="\t",

        index=False,
    )

    top_candidates.to_csv(
        paths["OUT"]
        /
        "top_mechanistic_candidates.tsv",

        sep="\t",

        index=False,
    )

    summary = {
        "STEP14_VERSION":
            VERSION,

        "PHENOTYPE":
            args.phenotype,

        "ANCESTRY_CODE":
            ancestry_code,

        "ANCESTRY_LABEL":
            ancestry_label,

        "N_STUDIES":
            int(
                all_variants[
                    "STUDY_ID"
                ].nunique()
            ),

        "N_VARIANTS":
            int(
                len(
                    all_variants
                )
            ),

        "N_LOCI":
            int(
                all_variants[
                    [
                        "STUDY_ID",
                        "LOCUS_ID",
                    ]
                ].drop_duplicates().shape[0]
            ),

        "N_CODING_OR_SPLICE":
            int(
                len(
                    coding
                )
            ),

        "N_NONCODING":
            int(
                len(
                    noncoding
                )
            ),

        "N_UNRESOLVED":
            int(
                len(
                    unresolved
                )
            ),

        "MECHANISM_CLASS_COUNTS":
            {
                str(k):
                    int(v)
                for k, v
                in all_variants[
                    "MECHANISM_CLASS"
                ].value_counts(
                    dropna=False
                ).items()
            },

        "RESOURCE_STATUS":
            resource_status.to_dict(
                orient="records"
            ),

        "EQTL_SCREEN_THRESHOLD":
            args.eqtl_screen,

        "SQTL_SCREEN_THRESHOLD":
            args.sqtl_screen,

        "SPLICEAI_SUPPORT_THRESHOLD":
            args.spliceai_support,

        "NOTE":
            (
                "Mechanism classes are descriptive evidence integration, "
                "not causal probabilities. Step11 LCLPP is a screen until "
                "formal colocalisation is added."
            ),

        "COMPLETED_UTC":
            datetime.now(
                timezone.utc
            ).isoformat(),
    }

    (
        paths["OUT"]
        /
        "mechanism_summary.json"
    ).write_text(
        json.dumps(
            summary,
            indent=2,
            default=json_safe,
        )
        +
        "\n",

        encoding="utf-8",
    )

    show(
        study_summary,
        "TABLE 1 - STUDY MECHANISM SUMMARY",
        args.max_print,
    )

    show(
        locus_summary,
        "TABLE 2 - LOCUS MECHANISM SUMMARY",
        args.max_print,
    )

    useful = [
        c
        for c in [
            "STUDY_ID",
            "LOCUS_ID",
            "VARIANT_KEY",
            "PIP",
            "IN_95_CREDIBLE_SET",
            "VARIANT_CONTEXT",
            "MECHANISM_CLASS",
            "PRIMARY_GENE",
            "Consequence",
            "IMPACT",
            "HGVSp",
            "SIFT",
            "PolyPhen",
            "DOMAINS",
            "EQTL_GENE",
            "EQTL_TISSUE",
            "EQTL_LCLPP",
            "SQTL_GENE",
            "SQTL_TISSUE",
            "SQTL_LCLPP",
            "SPLICEAI_MAX_DS",
            "PANGOLIN_MAX_ABS",
            "OT_LOCUS_STATUS",
            "OT_METHOD",
            "FOLLOWUP_REQUIREMENTS",
        ]
        if c in top_candidates.columns
    ]

    show(
        top_candidates[
            useful
        ],
        "TABLE 3 - TOP MECHANISTIC CANDIDATE PER STUDY LOCUS",
        args.max_print,
    )

    section(
        "STEP14 COMPLETE"
    )

    print(
        f"Studies         : "
        f"{all_variants['STUDY_ID'].nunique():,}"
    )

    print(
        f"Variants        : "
        f"{len(all_variants):,}"
    )

    print(
        f"Study-loci      : "
        f"{locus_summary.shape[0]:,}"
    )

    print(
        f"Coding/splice   : "
        f"{len(coding):,}"
    )

    print(
        f"Noncoding       : "
        f"{len(noncoding):,}"
    )

    print(
        f"Unresolved      : "
        f"{len(unresolved):,}"
    )

    print()
    print(
        "Next scientific upgrade:"
    )

    print(
        "  add setup-managed ClinVar + AlphaMissense + "
        "CADD + gnomAD constraint + Mendelian gene-disease resources,"
    )

    print(
        "  then add LOFTEE to Step07 VEP and formal "
        "colocalisation validation."
    )


if __name__ == "__main__":
    main()
