#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Generic GWAS Pipeline
STEP 08 - GTEx v11 eQTL + sQTL integration (ALL tissues)

This step is phenotype-agnostic. It never chooses tissues from the phenotype.
Every eligible study is scanned against ALL locally available GTEx v11
single-tissue significant eQTL and sQTL association files.

MODES
=====

1) Planner

    python Step08_Integrate_GTEx_eQTL_sQTL.py \
        --phenotype migraine \
        --ancestry EUR

Creates:
    08_qtl/<phenotype>/<ancestry>/qtl_manifest.tsv
    Step08_GTEx_QTL_<phenotype>_<ancestry>.sh

2) Direct one-index execution

    python Step08_Integrate_GTEx_eQTL_sQTL.py \
        --phenotype migraine \
        --ancestry EUR \
        --index 1

3) SLURM-array worker

The generated bash exports:
    SLURM_ARRAY_TASK_ID
    GWAS_QTL_MANIFEST

SCIENTIFIC INPUT
================

Step 07 per-study main table:
    07_annotation/<phenotype>/<ancestry>/<GCST>/
        <GCST>_VEP_variant_summary.tsv

LOCAL GTEx v11 RESOURCES
========================

The script expects the resources generated by Step00_Check_Resources.py:

    resources/gtex/v11/qtl/eQTL/
    resources/gtex/v11/qtl/sQTL/
    resources/gtex/v11/reference/
      GTEx_Analysis_2021-02-11_v11_WholeGenomeSeq_953Indiv.lookup_table.txt.gz

It scans all significant-pair files discovered below eQTL and sQTL.
No GTEx API and no phenotype-specific tissue list are used.

SHARED CACHE
============

To avoid rescanning the multi-GB GTEx files once per GWAS, the first worker
builds a shared cache from the UNION of all Step-07 variants in the manifest.
An fcntl file lock prevents two SLURM tasks from building it simultaneously.
Other workers reuse the completed cache.

OUTPUT
======

08_qtl/<phenotype>/<ancestry>/
    qtl_manifest.tsv
    qtl_excluded_studies.tsv

    shared/
        GTEx_v11_target_variants.tsv.gz
        GTEx_v11_variant_mapping.tsv.gz
        GTEx_v11_eQTL_target_matches.tsv.gz
        GTEx_v11_sQTL_target_matches.tsv.gz
        GTEx_v11_files_scanned.tsv
        GTEx_v11_cache_summary.json
        GTEx_v11_cache.complete

    <GCST>/
        <GCST>_GTEx_variant_mapping.tsv
        <GCST>_GTEx_eQTL.tsv.gz
        <GCST>_GTEx_sQTL.tsv.gz
        <GCST>_GTEx_variant_gene_evidence.tsv.gz
        <GCST>_GTEx_QTL_variant_summary.tsv
        <GCST>_GTEx_QTL_locus_summary.tsv
        qtl_summary.json
        QTL_FAILED.txt   # hard failure only

INTERPRETATION
==============

HAS_GTEX_EQTL=False or HAS_GTEX_SQTL=False means that no significant
association was found in the local GTEx v11 significant-pair resources.
It does NOT prove absence of a regulatory effect.
"""

from __future__ import annotations

import argparse
import fcntl
import hashlib
import json
import os
import re
import shlex
import sys
import traceback
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd


STEP08_VERSION = "1.0.0"

DEFAULT_PARTITION = "general"
DEFAULT_TIME = "24:00:00"
DEFAULT_MEMORY = "64G"
DEFAULT_CPUS = 4
DEFAULT_MAX_PARALLEL = 2
DEFAULT_CHUNK_SIZE = 500_000

ANCESTRY_ALIASES = {
    "eur": ("EUR", "European"),
    "european": ("EUR", "European"),
    "afr": ("AFR", "African"),
    "african": ("AFR", "African"),
    "eas": ("EAS", "East Asian"),
    "east asian": ("EAS", "East Asian"),
    "sas": ("SAS", "South Asian"),
    "south asian": ("SAS", "South Asian"),
    "amr": ("AMR", "Hispanic or Latin American"),
    "hispanic": ("AMR", "Hispanic or Latin American"),
    "latino": ("AMR", "Hispanic or Latin American"),
    "hispanic or latin american": ("AMR", "Hispanic or Latin American"),
}


# =============================================================================
# GENERIC HELPERS
# =============================================================================

def banner(text: str) -> None:
    print()
    print("=" * 104)
    print(text)
    print("=" * 104)


def normalize_text(value) -> str:
    text = str(value).lower()
    text = re.sub(r"[^a-z0-9]+", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def slugify(value) -> str:
    return normalize_text(value).replace(" ", "_")


def canonical_ancestry(value: str) -> tuple[str, str]:
    key = normalize_text(value)
    if key not in ANCESTRY_ALIASES:
        raise ValueError(
            f"Unsupported ancestry: {value!r}. "
            "Use EUR, AFR, EAS, SAS, AMR or the corresponding full label."
        )
    return ANCESTRY_ALIASES[key]


def parse_walltime(value: str) -> int:
    text = str(value).strip()
    days = 0
    if "-" in text:
        day_text, text = text.split("-", 1)
        days = int(day_text)
    parts = text.split(":")
    if len(parts) != 3:
        raise ValueError("Walltime must be HH:MM:SS or D-HH:MM:SS")
    hours, minutes, seconds = map(int, parts)
    if days < 0 or hours < 0 or not 0 <= minutes < 60 or not 0 <= seconds < 60:
        raise ValueError("Invalid walltime")
    return days * 86400 + hours * 3600 + minutes * 60 + seconds


def validate_walltime(value: str) -> str:
    seconds = parse_walltime(value)
    if seconds <= 0:
        raise ValueError("Walltime must be greater than zero")
    if seconds > 86400:
        raise ValueError("Maximum allowed walltime is 24 hours")
    return value


def safe_read_json(path: Path) -> dict:
    if not path.exists() or path.stat().st_size == 0:
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


def write_json(path: Path, payload: dict) -> None:
    path.write_text(
        json.dumps(payload, indent=2, default=str),
        encoding="utf-8",
    )


def first_existing(columns, candidates):
    lookup = {str(c).lower(): c for c in columns}
    for candidate in candidates:
        if candidate.lower() in lookup:
            return lookup[candidate.lower()]
    return None


def collapse(values) -> str:
    output = []
    for value in pd.Series(values).dropna().astype(str):
        for token in value.split(";"):
            token = token.strip()
            if token and token.lower() not in {"nan", "none", "."} and token not in output:
                output.append(token)
    return ";".join(output)


def safe_numeric_min(series):
    x = pd.to_numeric(series, errors="coerce").dropna()
    return float(x.min()) if not x.empty else np.nan


def safe_numeric_max_abs(series):
    x = pd.to_numeric(series, errors="coerce").dropna()
    return float(x.abs().max()) if not x.empty else np.nan


def sha256_strings(values) -> str:
    h = hashlib.sha256()
    for value in sorted(str(v) for v in values):
        h.update(value.encode("utf-8"))
        h.update(b"\n")
    return h.hexdigest()


def read_resource_env(root: Path) -> dict[str, str]:
    path = root / "resource_paths.env"
    result = {}
    if not path.exists():
        return result
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        if key.startswith("export "):
            key = key[7:].strip()
        value = value.strip().strip('"').strip("'")
        result[key] = value
    return result


# =============================================================================
# CLI
# =============================================================================

def arguments():
    parser = argparse.ArgumentParser(
        description=(
            "Integrate Step07 fine-mapped/VEP variants with ALL-tissue "
            "GTEx v11 significant eQTL and sQTL associations."
        )
    )
    parser.add_argument("--phenotype", required=True)
    parser.add_argument("--ancestry", required=True)
    parser.add_argument(
        "--index",
        type=int,
        default=None,
        help="Run exactly one QTL_TASK_ID from the existing Step08 manifest.",
    )
    parser.add_argument("--partition", default=DEFAULT_PARTITION)
    parser.add_argument("--time", default=DEFAULT_TIME)
    parser.add_argument("--memory", default=DEFAULT_MEMORY)
    parser.add_argument("--cpus", type=int, default=DEFAULT_CPUS)
    parser.add_argument("--max-parallel", type=int, default=DEFAULT_MAX_PARALLEL)
    parser.add_argument("--chunk-size", type=int, default=DEFAULT_CHUNK_SIZE)
    parser.add_argument(
        "--gtex-root",
        default=None,
        help=(
            "GTEx v11 resource root. Default: resource_paths.env GTEX_V11, "
            "then resources/gtex/v11."
        ),
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Rebuild the selected study outputs even if already complete.",
    )
    parser.add_argument(
        "--rebuild-cache",
        action="store_true",
        help="Force rebuilding the shared all-tissue GTEx target cache.",
    )
    return parser.parse_args()


def validate_arguments(args) -> None:
    if not args.phenotype.strip():
        raise ValueError("--phenotype cannot be empty")
    validate_walltime(args.time)
    if args.index is not None and args.index < 1:
        raise ValueError("--index must be >= 1")
    if args.cpus < 1:
        raise ValueError("--cpus must be >= 1")
    if args.max_parallel < 1:
        raise ValueError("--max-parallel must be >= 1")
    if args.chunk_size < 10_000:
        raise ValueError("--chunk-size must be >= 10000")


# =============================================================================
# GTEx RESOURCE DISCOVERY
# =============================================================================

def resolve_gtex_root(root: Path, explicit: str | None) -> Path:
    candidates = []
    if explicit:
        candidates.append(Path(explicit).expanduser())

    env_value = os.environ.get("GTEX_V11")
    if env_value:
        candidates.append(Path(env_value).expanduser())

    resource_env = read_resource_env(root)
    if resource_env.get("GTEX_V11"):
        candidates.append(Path(resource_env["GTEX_V11"]).expanduser())

    candidates.append(root / "resources" / "gtex" / "v11")

    for candidate in candidates:
        candidate = candidate.resolve()
        if candidate.exists() and candidate.is_dir():
            return candidate

    raise FileNotFoundError(
        "Could not find GTEx v11 resources. Pass --gtex-root or ensure "
        "resource_paths.env exports GTEX_V11."
    )


def discover_significant_pair_files(directory: Path, qtl_type: str) -> list[Path]:
    if not directory.exists():
        return []

    candidates = []
    for path in directory.rglob("*"):
        if not path.is_file():
            continue
        name = path.name.lower()
        if name.startswith("."):
            continue
        if not (
            name.endswith(".txt.gz")
            or name.endswith(".tsv.gz")
            or name.endswith(".txt")
            or name.endswith(".tsv")
        ):
            continue
        # We want significant pair-level outputs, not eGenes/sGenes summary tables.
        if "signif" not in name and "pair" not in name:
            continue
        if "egenes" in name or "sgenes" in name:
            continue
        candidates.append(path.resolve())

    # If naming differs in a future extraction, inspect headers as a fallback.
    if not candidates:
        for path in directory.rglob("*"):
            if not path.is_file():
                continue
            name = path.name.lower()
            if not (
                name.endswith(".txt.gz")
                or name.endswith(".tsv.gz")
                or name.endswith(".txt")
                or name.endswith(".tsv")
            ):
                continue
            try:
                header = pd.read_csv(path, sep="\t", nrows=0, compression="infer")
            except Exception:
                continue
            if first_existing(header.columns, ["variant_id", "variantId", "variant"]):
                if qtl_type == "EQTL" and first_existing(header.columns, ["gene_id", "geneId", "gencodeId"]):
                    candidates.append(path.resolve())
                elif qtl_type == "SQTL" and first_existing(
                    header.columns,
                    ["phenotype_id", "phenotypeId", "gene_id", "geneId", "gencodeId"],
                ):
                    candidates.append(path.resolve())

    return sorted(set(candidates))


def tissue_from_filename(path: Path) -> str:
    name = path.name
    suffix_patterns = [
        r"\.v11\.signif_variant_gene_pairs\.txt\.gz$",
        r"\.v11\.signif_variant_gene_pairs\.txt$",
        r"\.signif_variant_gene_pairs\.txt\.gz$",
        r"\.signif_variant_gene_pairs\.txt$",
        r"\.signif_pairs\.txt\.gz$",
        r"\.signif_pairs\.txt$",
        r"\.txt\.gz$",
        r"\.tsv\.gz$",
        r"\.txt$",
        r"\.tsv$",
    ]
    tissue = name
    for pattern in suffix_patterns:
        new = re.sub(pattern, "", tissue, flags=re.IGNORECASE)
        if new != tissue:
            tissue = new
            break
    # Remove common release/type prefixes/suffixes while preserving GTEx tissue IDs.
    tissue = re.sub(r"^GTEx_Analysis_v11_", "", tissue, flags=re.IGNORECASE)
    tissue = re.sub(r"_(eQTL|sQTL)$", "", tissue, flags=re.IGNORECASE)
    return tissue


def resource_signature(paths: list[Path]) -> str:
    records = []
    for path in sorted(paths):
        st = path.stat()
        records.append(f"{path}|{st.st_size}|{st.st_mtime_ns}")
    return sha256_strings(records)


# =============================================================================
# STEP 07 INPUT
# =============================================================================

def load_step07_variants(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path, sep="\t", low_memory=False)

    required = [
        "VEP_ID",
        "LOCUS_ID",
        "CHR",
        "REFERENCE_POS",
        "REFERENCE_REF",
        "REFERENCE_ALT",
        "PIP",
    ]
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise RuntimeError(
            f"Step07 variant summary is missing required columns {missing}:\n{path}"
        )

    df["CHR"] = (
        df["CHR"].astype(str).str.replace(r"^chr", "", regex=True, case=False)
    )
    df["CHR"] = pd.to_numeric(df["CHR"], errors="coerce")
    df["REFERENCE_POS"] = pd.to_numeric(df["REFERENCE_POS"], errors="coerce")
    df["PIP"] = pd.to_numeric(df["PIP"], errors="coerce")

    df = df.dropna(
        subset=[
            "VEP_ID",
            "LOCUS_ID",
            "CHR",
            "REFERENCE_POS",
            "REFERENCE_REF",
            "REFERENCE_ALT",
        ]
    ).copy()

    df = df[df["CHR"].between(1, 22, inclusive="both")].copy()
    df["CHR"] = df["CHR"].astype(int)
    df["REFERENCE_POS"] = df["REFERENCE_POS"].astype(int)
    df["REFERENCE_REF"] = df["REFERENCE_REF"].astype(str).str.upper().str.strip()
    df["REFERENCE_ALT"] = df["REFERENCE_ALT"].astype(str).str.upper().str.strip()

    # One Step07 row per VEP_ID is expected. Keep highest PIP if duplicates exist.
    df = (
        df.sort_values(["LOCUS_ID", "PIP"], ascending=[True, False], kind="stable")
        .drop_duplicates(subset=["VEP_ID"], keep="first")
        .reset_index(drop=True)
    )

    df["GTEX_CONSTRUCTED_VARIANT_ID"] = (
        "chr"
        + df["CHR"].astype(str)
        + "_"
        + df["REFERENCE_POS"].astype(str)
        + "_"
        + df["REFERENCE_REF"]
        + "_"
        + df["REFERENCE_ALT"]
        + "_b38"
    )

    df["GTEX_MATCH_KEY"] = (
        df["CHR"].astype(str)
        + ":"
        + df["REFERENCE_POS"].astype(str)
        + ":"
        + df["REFERENCE_REF"]
        + ":"
        + df["REFERENCE_ALT"]
    )

    return df


# =============================================================================
# PLANNER
# =============================================================================

def planner_mode(args) -> None:
    validate_arguments(args)

    root = Path.cwd().resolve()
    phenotype = args.phenotype.strip()
    phenotype_slug = slugify(phenotype)
    ancestry_code, ancestry_label = canonical_ancestry(args.ancestry)
    ancestry_slug = slugify(ancestry_label)

    pipeline_python = root / "envs" / "pipeline" / "bin" / "python"
    if not pipeline_python.exists():
        pipeline_python = Path(sys.executable).resolve()

    gtex_root = resolve_gtex_root(root, args.gtex_root)
    eqtl_root = gtex_root / "qtl" / "eQTL"
    sqtl_root = gtex_root / "qtl" / "sQTL"
    lookup_file = (
        gtex_root
        / "reference"
        / "GTEx_Analysis_2021-02-11_v11_WholeGenomeSeq_953Indiv.lookup_table.txt.gz"
    )

    eqtl_files = discover_significant_pair_files(eqtl_root, "EQTL")
    sqtl_files = discover_significant_pair_files(sqtl_root, "SQTL")

    if not eqtl_files:
        raise FileNotFoundError(
            f"No GTEx v11 eQTL significant-pair files found under:\n  {eqtl_root}"
        )
    if not sqtl_files:
        raise FileNotFoundError(
            f"No GTEx v11 sQTL significant-pair files found under:\n  {sqtl_root}"
        )

    annotation_root = root / "07_annotation" / phenotype_slug / ancestry_slug
    if not annotation_root.exists():
        raise FileNotFoundError(
            f"Step07 annotation directory does not exist:\n  {annotation_root}"
        )

    qtl_root = root / "08_qtl" / phenotype_slug / ancestry_slug
    log_root = root / "logs" / "step08_qtl" / phenotype_slug / ancestry_slug
    qtl_root.mkdir(parents=True, exist_ok=True)
    log_root.mkdir(parents=True, exist_ok=True)

    rows = []
    excluded = []

    for study_dir in sorted(annotation_root.glob("GCST*")):
        if not study_dir.is_dir():
            continue
        accession = study_dir.name
        summary_file = study_dir / "annotation_summary.json"
        summary = safe_read_json(summary_file)
        variant_file = study_dir / f"{accession}_VEP_variant_summary.tsv"

        reason = ""
        if not summary:
            reason = "Step07 annotation summary missing/unreadable"
        elif str(summary.get("STATUS", "")).upper() != "COMPLETE":
            reason = f"Step07 status is {summary.get('STATUS', 'UNKNOWN')}"
        elif not variant_file.exists() or variant_file.stat().st_size == 0:
            reason = "Step07 variant summary missing/empty"

        if reason:
            excluded.append(
                {
                    "STUDY_ACCESSION": accession,
                    "STEP07_STATUS": summary.get("STATUS", ""),
                    "REASON": reason,
                }
            )
            continue

        rows.append(
            {
                "QTL_TASK_ID": len(rows) + 1,
                "STUDY_ACCESSION": accession,
                "PHENOTYPE": phenotype,
                "ANCESTRY_CODE": ancestry_code,
                "ANCESTRY_LABEL": ancestry_label,
                "STEP07_VARIANT_FILE": str(variant_file.resolve()),
                "STEP07_SUMMARY_FILE": str(summary_file.resolve()),
                "OUTPUT_DIR": str((qtl_root / accession).resolve()),
                "GTEX_ROOT": str(gtex_root.resolve()),
                "GTEX_EQTL_ROOT": str(eqtl_root.resolve()),
                "GTEX_SQTL_ROOT": str(sqtl_root.resolve()),
                "GTEX_LOOKUP_FILE": str(lookup_file.resolve()),
                "CHUNK_SIZE": int(args.chunk_size),
                "FORCE": bool(args.force),
                "REBUILD_CACHE": bool(args.rebuild_cache),
                "STEP08_VERSION": STEP08_VERSION,
            }
        )

    excluded_file = qtl_root / "qtl_excluded_studies.tsv"
    pd.DataFrame(
        excluded,
        columns=["STUDY_ACCESSION", "STEP07_STATUS", "REASON"],
    ).to_csv(excluded_file, sep="\t", index=False)

    if not rows:
        raise RuntimeError(
            "No completed Step07 studies are currently eligible for Step08.\n"
            f"Inspect:\n  {excluded_file}"
        )

    manifest = pd.DataFrame(rows)
    manifest_file = (qtl_root / "qtl_manifest.tsv").resolve()
    manifest.to_csv(manifest_file, sep="\t", index=False)

    bash_file = root / f"Step08_GTEx_QTL_{phenotype_slug}_{ancestry_slug}.sh"
    script_path = Path(__file__).resolve()
    array_spec = f"1-{len(manifest)}%{args.max_parallel}"
    job_name = f"GTEx_{phenotype_slug}_{ancestry_code.lower()}"[:100]

    bash_text = f'''#!/bin/bash
#SBATCH --job-name={job_name}
#SBATCH --nodes=1
#SBATCH --partition={args.partition}
#SBATCH --time={args.time}
#SBATCH --output={log_root}/qtl.%A_%a.out
#SBATCH --error={log_root}/qtl.%A_%a.err
#SBATCH --array={array_spec}
#SBATCH --mem={args.memory}
#SBATCH --cpus-per-task={args.cpus}
#SBATCH --ntasks=1

set -euo pipefail

cd {shlex.quote(str(root))}

export GWAS_QTL_MANIFEST={shlex.quote(str(manifest_file))}

printf '%s\n' '=============================================================='
printf '%s\n' 'STEP 08 - GTEx v11 ALL-TISSUE eQTL + sQTL'
printf '%s\n' '=============================================================='
printf 'Job ID        : %s\n' "$SLURM_JOB_ID"
printf 'Array task ID : %s\n' "$SLURM_ARRAY_TASK_ID"
printf 'Phenotype     : %s\n' {shlex.quote(phenotype)}
printf 'Ancestry      : %s (%s)\n' {shlex.quote(ancestry_label)} {shlex.quote(ancestry_code)}
printf 'GTEx root     : %s\n' {shlex.quote(str(gtex_root))}
printf 'Mode          : ALL TISSUES\n'
printf 'Hostname      : %s\n' "$(hostname)"
printf '%s\n' '=============================================================='

{shlex.quote(str(pipeline_python))} {shlex.quote(str(script_path))}

printf '%s\n' '=============================================================='
printf 'STEP 08 TASK COMPLETE: %s\n' "$SLURM_ARRAY_TASK_ID"
printf '%s\n' '=============================================================='
'''
    bash_file.write_text(bash_text, encoding="utf-8")
    bash_file.chmod(0o755)

    banner("STEP 08 - GTEx v11 ALL-TISSUE QTL PLANNER")
    print(f"Phenotype          : {phenotype}")
    print(f"Ancestry           : {ancestry_label} ({ancestry_code})")
    print(f"Eligible studies   : {len(manifest)}")
    print(f"Excluded studies   : {len(excluded)}")
    print(f"GTEx root          : {gtex_root}")
    print(f"eQTL files         : {len(eqtl_files)}")
    print(f"sQTL files         : {len(sqtl_files)}")
    print(f"Lookup table       : {lookup_file if lookup_file.exists() else 'MISSING - constructed IDs will be used'}")
    print("Tissue policy      : ALL GTEx tissues (no phenotype-specific filtering)")
    print(f"Chunk size         : {args.chunk_size:,}")
    print(f"Array              : {array_spec}")
    print()
    print(
        manifest[["QTL_TASK_ID", "STUDY_ACCESSION", "STEP07_VARIANT_FILE"]]
        .to_string(index=False)
    )
    print()
    print(f"Manifest:\n  {manifest_file}")
    print(f"Excluded:\n  {excluded_file}")
    print(f"Generated SLURM:\n  {bash_file}")
    print()
    print("NEXT COMMAND:")
    print()
    print(f"  sbatch {bash_file.name}")
    print()


# =============================================================================
# GTEx LOOKUP TABLE EXACT MAPPING
# =============================================================================

def map_targets_with_lookup(targets: pd.DataFrame, lookup_file: Path, chunk_size: int) -> pd.DataFrame:
    result = targets[[
        "GTEX_MATCH_KEY",
        "GTEX_CONSTRUCTED_VARIANT_ID",
        "CHR",
        "REFERENCE_POS",
        "REFERENCE_REF",
        "REFERENCE_ALT",
    ]].drop_duplicates().copy()

    result["GTEX_VARIANT_ID"] = result["GTEX_CONSTRUCTED_VARIANT_ID"]
    result["GTEX_SNP_ID"] = pd.Series([None] * len(result), index=result.index, dtype="object")
    result["GTEX_MAPPING_METHOD"] = "CONSTRUCTED_GRCH38"

    if not lookup_file.exists() or lookup_file.stat().st_size == 0:
        return result

    try:
        header = pd.read_csv(lookup_file, sep="\t", nrows=0, compression="infer")
    except Exception as error:
        print(f"WARNING: could not read GTEx lookup header: {error}")
        return result

    variant_col = first_existing(
        header.columns,
        ["variant_id", "variantId", "variant", "variant_id_b38"],
    )
    chr_col = first_existing(header.columns, ["chr", "chromosome", "chrom"])
    pos_col = first_existing(header.columns, ["pos", "position", "variant_pos"])
    ref_col = first_existing(header.columns, ["ref", "reference", "ref_allele"])
    alt_col = first_existing(header.columns, ["alt", "alternate", "alt_allele"])
    snp_col = first_existing(header.columns, ["snp_id", "snpId", "rs_id", "rsid"])

    # Many GTEx lookup tables contain only variant_id + rsID. In that case the
    # constructed b38 ID itself is already the exact lookup key.
    if variant_col is None:
        return result

    target_ids = set(result["GTEX_CONSTRUCTED_VARIANT_ID"].astype(str))
    matches = []

    usecols = [variant_col]
    if snp_col:
        usecols.append(snp_col)
    for c in (chr_col, pos_col, ref_col, alt_col):
        if c and c not in usecols:
            usecols.append(c)

    try:
        iterator = pd.read_csv(
            lookup_file,
            sep="\t",
            usecols=usecols,
            chunksize=chunk_size,
            compression="infer",
            low_memory=False,
        )

        for chunk in iterator:
            ids = chunk[variant_col].astype(str)
            hit = chunk.loc[ids.isin(target_ids)].copy()
            if not hit.empty:
                matches.append(hit)
    except Exception as error:
        print(f"WARNING: GTEx lookup scan failed; using constructed IDs: {error}")
        return result

    if not matches:
        return result

    mapped = pd.concat(matches, ignore_index=True)
    mapped = mapped.drop_duplicates(subset=[variant_col], keep="first")
    mapped = mapped.rename(columns={variant_col: "GTEX_VARIANT_ID_LOOKUP"})
    if snp_col:
        mapped = mapped.rename(columns={snp_col: "GTEX_SNP_ID_LOOKUP"})

    lookup_map = mapped.set_index("GTEX_VARIANT_ID_LOOKUP").to_dict(orient="index")

    for idx, row in result.iterrows():
        cid = str(row["GTEX_CONSTRUCTED_VARIANT_ID"])
        if cid in lookup_map:
            record = lookup_map[cid]
            result.at[idx, "GTEX_VARIANT_ID"] = cid
            result.at[idx, "GTEX_MAPPING_METHOD"] = "GTEX_V11_LOOKUP_EXACT"
            if "GTEX_SNP_ID_LOOKUP" in record:
                result.at[idx, "GTEX_SNP_ID"] = record.get("GTEX_SNP_ID_LOOKUP")

    return result


# =============================================================================
# GTEx SIGNIFICANT-PAIR SCANNING
# =============================================================================

def normalize_qtl_hits(
    raw: pd.DataFrame,
    qtl_type: str,
    tissue: str,
    source_file: Path,
) -> pd.DataFrame:
    if raw.empty:
        return pd.DataFrame(
            columns=[
                "GTEX_VARIANT_ID",
                "QTL_TYPE",
                "GTEX_TISSUE",
                "GTEX_GENE_ID",
                "GTEX_PHENOTYPE_ID",
                "GTEX_PVALUE",
                "GTEX_NES",
                "GTEX_SLOPE_SE",
                "GTEX_MAF",
                "SOURCE_FILE",
            ]
        )

    variant_col = first_existing(raw.columns, ["variant_id", "variantId", "variant"])
    if variant_col is None:
        return pd.DataFrame()

    gene_col = first_existing(
        raw.columns,
        ["gene_id", "geneId", "gencodeId", "gencode_id", "gene"],
    )
    phenotype_col = first_existing(
        raw.columns,
        ["phenotype_id", "phenotypeId", "phenotype", "intron_id", "cluster_id"],
    )
    p_col = first_existing(
        raw.columns,
        ["pval_nominal", "p_value", "pvalue", "pval", "pValue"],
    )
    nes_col = first_existing(
        raw.columns,
        ["slope", "nes", "NES", "beta", "effect_size"],
    )
    se_col = first_existing(
        raw.columns,
        ["slope_se", "se", "standard_error", "beta_se"],
    )
    maf_col = first_existing(raw.columns, ["maf", "MAF", "minor_allele_frequency"])

    out = pd.DataFrame()
    out["GTEX_VARIANT_ID"] = raw[variant_col].astype(str)
    out["QTL_TYPE"] = qtl_type
    out["GTEX_TISSUE"] = tissue
    out["GTEX_GENE_ID"] = raw[gene_col].astype(str) if gene_col else np.nan
    out["GTEX_PHENOTYPE_ID"] = raw[phenotype_col].astype(str) if phenotype_col else np.nan
    out["GTEX_PVALUE"] = pd.to_numeric(raw[p_col], errors="coerce") if p_col else np.nan
    out["GTEX_NES"] = pd.to_numeric(raw[nes_col], errors="coerce") if nes_col else np.nan
    out["GTEX_SLOPE_SE"] = pd.to_numeric(raw[se_col], errors="coerce") if se_col else np.nan
    out["GTEX_MAF"] = pd.to_numeric(raw[maf_col], errors="coerce") if maf_col else np.nan
    out["SOURCE_FILE"] = str(source_file)

    # Keep raw IDs clean rather than literal 'nan'.
    for col in ["GTEX_GENE_ID", "GTEX_PHENOTYPE_ID"]:
        out[col] = out[col].replace({"nan": np.nan, "None": np.nan, "": np.nan})

    return out


def scan_qtl_files(
    files: list[Path],
    qtl_type: str,
    target_variant_ids: set[str],
    chunk_size: int,
) -> tuple[pd.DataFrame, list[dict]]:
    matches = []
    audit = []

    for number, path in enumerate(files, start=1):
        tissue = tissue_from_filename(path)
        n_rows = 0
        n_hits = 0
        status = "OK"
        error_text = ""

        print(
            f"[{qtl_type}] {number:>3}/{len(files):<3} "
            f"{tissue:<40} {path.name}",
            flush=True,
        )

        try:
            header = pd.read_csv(path, sep="\t", nrows=0, compression="infer")
            variant_col = first_existing(
                header.columns,
                ["variant_id", "variantId", "variant"],
            )
            if variant_col is None:
                status = "SKIPPED_NO_VARIANT_ID"
            else:
                iterator = pd.read_csv(
                    path,
                    sep="\t",
                    chunksize=chunk_size,
                    compression="infer",
                    low_memory=False,
                )
                for chunk in iterator:
                    n_rows += len(chunk)
                    ids = chunk[variant_col].astype(str)
                    hit = chunk.loc[ids.isin(target_variant_ids)].copy()
                    if hit.empty:
                        continue
                    n_hits += len(hit)
                    normalized = normalize_qtl_hits(
                        hit,
                        qtl_type=qtl_type,
                        tissue=tissue,
                        source_file=path,
                    )
                    if not normalized.empty:
                        matches.append(normalized)
        except Exception as error:
            status = "ERROR"
            error_text = f"{type(error).__name__}: {error}"

        audit.append(
            {
                "QTL_TYPE": qtl_type,
                "TISSUE": tissue,
                "SOURCE_FILE": str(path),
                "N_ROWS_SCANNED": n_rows,
                "N_TARGET_MATCH_ROWS": n_hits,
                "STATUS": status,
                "ERROR": error_text,
            }
        )

    if matches:
        combined = pd.concat(matches, ignore_index=True)
        subset = [
            c
            for c in [
                "GTEX_VARIANT_ID",
                "QTL_TYPE",
                "GTEX_TISSUE",
                "GTEX_GENE_ID",
                "GTEX_PHENOTYPE_ID",
            ]
            if c in combined.columns
        ]
        combined = combined.drop_duplicates(subset=subset, keep="first")
    else:
        combined = pd.DataFrame(
            columns=[
                "GTEX_VARIANT_ID",
                "QTL_TYPE",
                "GTEX_TISSUE",
                "GTEX_GENE_ID",
                "GTEX_PHENOTYPE_ID",
                "GTEX_PVALUE",
                "GTEX_NES",
                "GTEX_SLOPE_SE",
                "GTEX_MAF",
                "SOURCE_FILE",
            ]
        )

    return combined, audit


# =============================================================================
# SHARED UNION CACHE
# =============================================================================

def shared_paths(qtl_root: Path) -> dict[str, Path]:
    shared = qtl_root / "shared"
    shared.mkdir(parents=True, exist_ok=True)
    return {
        "dir": shared,
        "lock": shared / ".GTEx_v11_cache.lock",
        "targets": shared / "GTEx_v11_target_variants.tsv.gz",
        "mapping": shared / "GTEx_v11_variant_mapping.tsv.gz",
        "eqtl": shared / "GTEx_v11_eQTL_target_matches.tsv.gz",
        "sqtl": shared / "GTEx_v11_sQTL_target_matches.tsv.gz",
        "audit": shared / "GTEx_v11_files_scanned.tsv",
        "summary": shared / "GTEx_v11_cache_summary.json",
        "complete": shared / "GTEx_v11_cache.complete",
    }


def collect_union_targets(manifest: pd.DataFrame) -> pd.DataFrame:
    frames = []
    for _, row in manifest.iterrows():
        accession = str(row["STUDY_ACCESSION"])
        path = Path(row["STEP07_VARIANT_FILE"]).resolve()
        variants = load_step07_variants(path)
        variants["STUDY_ACCESSION"] = accession
        frames.append(
            variants[
                [
                    "STUDY_ACCESSION",
                    "VEP_ID",
                    "CHR",
                    "REFERENCE_POS",
                    "REFERENCE_REF",
                    "REFERENCE_ALT",
                    "GTEX_CONSTRUCTED_VARIANT_ID",
                    "GTEX_MATCH_KEY",
                ]
            ]
        )
    union = pd.concat(frames, ignore_index=True)
    return union.drop_duplicates(
        subset=["GTEX_MATCH_KEY"],
        keep="first",
    ).reset_index(drop=True)


def cache_is_current(
    paths: dict[str, Path],
    target_hash: str,
    resource_hash: str,
) -> bool:
    if not paths["complete"].exists():
        return False
    required = [paths["targets"], paths["mapping"], paths["eqtl"], paths["sqtl"], paths["summary"]]
    if not all(p.exists() and p.stat().st_size > 0 for p in required):
        return False
    summary = safe_read_json(paths["summary"])
    return (
        summary.get("STEP08_VERSION") == STEP08_VERSION
        and summary.get("TARGET_HASH") == target_hash
        and summary.get("RESOURCE_HASH") == resource_hash
        and summary.get("TISSUE_POLICY") == "ALL_GTEX_V11_TISSUES"
    )


def ensure_shared_cache(
    manifest: pd.DataFrame,
    qtl_root: Path,
    force_rebuild: bool,
) -> dict[str, Path]:
    paths = shared_paths(qtl_root)

    gtex_root = Path(manifest.iloc[0]["GTEX_ROOT"]).resolve()
    eqtl_root = Path(manifest.iloc[0]["GTEX_EQTL_ROOT"]).resolve()
    sqtl_root = Path(manifest.iloc[0]["GTEX_SQTL_ROOT"]).resolve()
    lookup_file = Path(manifest.iloc[0]["GTEX_LOOKUP_FILE"]).resolve()
    chunk_size = int(manifest.iloc[0]["CHUNK_SIZE"])

    eqtl_files = discover_significant_pair_files(eqtl_root, "EQTL")
    sqtl_files = discover_significant_pair_files(sqtl_root, "SQTL")
    if not eqtl_files or not sqtl_files:
        raise RuntimeError(
            "GTEx significant-pair files disappeared after planning. "
            f"eQTL={len(eqtl_files)}, sQTL={len(sqtl_files)}"
        )

    union = collect_union_targets(manifest)
    target_hash = sha256_strings(union["GTEX_MATCH_KEY"].tolist())
    resource_hash = resource_signature(eqtl_files + sqtl_files + ([lookup_file] if lookup_file.exists() else []))

    with open(paths["lock"], "w", encoding="utf-8") as lock_handle:
        print("Waiting for shared GTEx cache lock if another task is building it...", flush=True)
        fcntl.flock(lock_handle.fileno(), fcntl.LOCK_EX)

        if not force_rebuild and cache_is_current(paths, target_hash, resource_hash):
            print("Shared GTEx v11 cache is current; reusing it.")
            return paths

        banner("BUILDING SHARED GTEx v11 ALL-TISSUE CACHE")
        print(f"Target variants      : {len(union):,}")
        print(f"eQTL tissue files    : {len(eqtl_files):,}")
        print(f"sQTL tissue files    : {len(sqtl_files):,}")
        print(f"GTEx root            : {gtex_root}")
        print("Tissue policy        : ALL GTEx v11 tissues")

        for key in ["complete", "targets", "mapping", "eqtl", "sqtl", "audit", "summary"]:
            p = paths[key]
            if p.exists():
                p.unlink()

        union.to_csv(paths["targets"], sep="\t", index=False, compression="gzip")

        mapping = map_targets_with_lookup(union, lookup_file, chunk_size)
        mapping.to_csv(paths["mapping"], sep="\t", index=False, compression="gzip")

        target_ids = set(mapping["GTEX_VARIANT_ID"].dropna().astype(str))
        target_ids.update(mapping["GTEX_CONSTRUCTED_VARIANT_ID"].dropna().astype(str))

        banner("SCANNING ALL GTEx v11 eQTL TISSUES")
        eqtl, audit_eqtl = scan_qtl_files(
            eqtl_files,
            qtl_type="EQTL",
            target_variant_ids=target_ids,
            chunk_size=chunk_size,
        )
        eqtl.to_csv(paths["eqtl"], sep="\t", index=False, compression="gzip")

        banner("SCANNING ALL GTEx v11 sQTL TISSUES")
        sqtl, audit_sqtl = scan_qtl_files(
            sqtl_files,
            qtl_type="SQTL",
            target_variant_ids=target_ids,
            chunk_size=chunk_size,
        )
        sqtl.to_csv(paths["sqtl"], sep="\t", index=False, compression="gzip")

        audit = pd.DataFrame(audit_eqtl + audit_sqtl)
        audit.to_csv(paths["audit"], sep="\t", index=False)

        summary = {
            "STEP08_VERSION": STEP08_VERSION,
            "GTEX_RELEASE": "v11",
            "GENOME_BUILD": "GRCh38",
            "TISSUE_POLICY": "ALL_GTEX_V11_TISSUES",
            "GTEX_ROOT": str(gtex_root),
            "N_TARGET_VARIANTS": int(len(union)),
            "N_EQTL_FILES": int(len(eqtl_files)),
            "N_SQTL_FILES": int(len(sqtl_files)),
            "N_EQTL_MATCH_ROWS": int(len(eqtl)),
            "N_SQTL_MATCH_ROWS": int(len(sqtl)),
            "N_EQTL_TARGET_VARIANTS": int(eqtl["GTEX_VARIANT_ID"].nunique()) if not eqtl.empty else 0,
            "N_SQTL_TARGET_VARIANTS": int(sqtl["GTEX_VARIANT_ID"].nunique()) if not sqtl.empty else 0,
            "TARGET_HASH": target_hash,
            "RESOURCE_HASH": resource_hash,
            "BUILT_UTC": datetime.now(timezone.utc).isoformat(),
        }
        write_json(paths["summary"], summary)
        paths["complete"].write_text("complete\n", encoding="utf-8")

        banner("SHARED GTEx CACHE COMPLETE")
        print(f"eQTL matched rows : {len(eqtl):,}")
        print(f"sQTL matched rows : {len(sqtl):,}")

    return paths


# =============================================================================
# PER-STUDY SUMMARIES
# =============================================================================

def add_variant_context(qtl: pd.DataFrame, variants: pd.DataFrame) -> pd.DataFrame:
    if qtl.empty:
        return qtl.copy()

    # Allow matching by the exact lookup ID or the deterministic constructed ID.
    id_to_vep = {}
    for _, row in variants.iterrows():
        seen_ids = set()
        for col in ["GTEX_VARIANT_ID", "GTEX_CONSTRUCTED_VARIANT_ID"]:
            value = row.get(col)
            if pd.isna(value) or not str(value):
                continue
            value = str(value)
            if value in seen_ids:
                continue
            seen_ids.add(value)
            bucket = id_to_vep.setdefault(value, [])
            if not any(str(existing.get("VEP_ID")) == str(row.get("VEP_ID")) for existing in bucket):
                bucket.append(row)

    output_rows = []
    for _, qrow in qtl.iterrows():
        variant_id = str(qrow["GTEX_VARIANT_ID"])
        contexts = id_to_vep.get(variant_id, [])
        for context in contexts:
            record = context.to_dict()
            record.update(qrow.to_dict())
            output_rows.append(record)

    return pd.DataFrame(output_rows)


def make_variant_gene_evidence(eqtl: pd.DataFrame, sqtl: pd.DataFrame) -> pd.DataFrame:
    frames = [x for x in [eqtl, sqtl] if x is not None and not x.empty]
    if not frames:
        return pd.DataFrame(
            columns=[
                "VEP_ID",
                "LOCUS_ID",
                "GTEX_GENE_ID",
                "GTEX_PHENOTYPE_ID",
                "HAS_EQTL",
                "HAS_SQTL",
                "QTL_TYPES",
                "TISSUES",
                "N_TISSUES",
                "MIN_QTL_P",
                "MAX_ABS_NES",
                "N_EQTL_ASSOCIATIONS",
                "N_SQTL_ASSOCIATIONS",
                "MIN_EQTL_P",
                "MIN_SQTL_P",
                "PIP",
            ]
        )

    qtl = pd.concat(frames, ignore_index=True)
    gene_key = qtl["GTEX_GENE_ID"].fillna("").astype(str)
    phenotype_key = qtl["GTEX_PHENOTYPE_ID"].fillna("").astype(str)
    qtl["QTL_TARGET_KEY"] = np.where(gene_key != "", gene_key, phenotype_key)

    rows = []
    for (vep_id, locus_id, target), group in qtl.groupby(
        ["VEP_ID", "LOCUS_ID", "QTL_TARGET_KEY"],
        dropna=False,
    ):
        eq = group[group["QTL_TYPE"] == "EQTL"]
        sq = group[group["QTL_TYPE"] == "SQTL"]
        rows.append(
            {
                "VEP_ID": vep_id,
                "LOCUS_ID": locus_id,
                "QTL_TARGET_KEY": target,
                "GTEX_GENE_ID": collapse(group["GTEX_GENE_ID"]),
                "GTEX_PHENOTYPE_ID": collapse(group["GTEX_PHENOTYPE_ID"]),
                "HAS_EQTL": not eq.empty,
                "HAS_SQTL": not sq.empty,
                "QTL_TYPES": collapse(group["QTL_TYPE"]),
                "TISSUES": collapse(group["GTEX_TISSUE"]),
                "N_TISSUES": int(group["GTEX_TISSUE"].nunique()),
                "MIN_QTL_P": safe_numeric_min(group["GTEX_PVALUE"]),
                "MAX_ABS_NES": safe_numeric_max_abs(group["GTEX_NES"]),
                "N_EQTL_ASSOCIATIONS": int(len(eq)),
                "N_SQTL_ASSOCIATIONS": int(len(sq)),
                "MIN_EQTL_P": safe_numeric_min(eq["GTEX_PVALUE"]) if not eq.empty else np.nan,
                "MIN_SQTL_P": safe_numeric_min(sq["GTEX_PVALUE"]) if not sq.empty else np.nan,
                "PIP": pd.to_numeric(group["PIP"], errors="coerce").max(),
            }
        )

    output = pd.DataFrame(rows)
    if not output.empty:
        output = output.sort_values(
            ["LOCUS_ID", "PIP", "MIN_QTL_P"],
            ascending=[True, False, True],
            kind="stable",
        )
    return output


def top_qtl_record(group: pd.DataFrame) -> dict:
    if group.empty:
        return {}
    p = pd.to_numeric(group["GTEX_PVALUE"], errors="coerce")
    if p.notna().any():
        return group.loc[p.idxmin()].to_dict()
    return group.iloc[0].to_dict()


def build_variant_summary(variants: pd.DataFrame, eqtl: pd.DataFrame, sqtl: pd.DataFrame) -> pd.DataFrame:
    frames = [x for x in [eqtl, sqtl] if x is not None and not x.empty]
    if frames:
        all_qtl = pd.concat(frames, ignore_index=True)
        grouped = {key: group for key, group in all_qtl.groupby("VEP_ID")}
    else:
        grouped = {}

    rows = []
    for _, variant in variants.iterrows():
        vep_id = variant["VEP_ID"]
        group = grouped.get(vep_id, pd.DataFrame())
        if group.empty:
            eq = pd.DataFrame()
            sq = pd.DataFrame()
        else:
            eq = group[group["QTL_TYPE"] == "EQTL"]
            sq = group[group["QTL_TYPE"] == "SQTL"]

        record = variant.to_dict()
        record["HAS_GTEX_EQTL"] = not eq.empty
        record["N_GTEX_EQTL_ASSOCIATIONS"] = int(len(eq))
        record["N_GTEX_EQTL_TISSUES"] = int(eq["GTEX_TISSUE"].nunique()) if not eq.empty else 0
        record["GTEX_EQTL_TISSUES"] = collapse(eq["GTEX_TISSUE"]) if not eq.empty else ""
        record["GTEX_EQTL_GENES"] = collapse(eq["GTEX_GENE_ID"]) if not eq.empty else ""
        record["MIN_GTEX_EQTL_P"] = safe_numeric_min(eq["GTEX_PVALUE"]) if not eq.empty else np.nan
        record["MAX_ABS_GTEX_EQTL_NES"] = safe_numeric_max_abs(eq["GTEX_NES"]) if not eq.empty else np.nan

        record["HAS_GTEX_SQTL"] = not sq.empty
        record["N_GTEX_SQTL_ASSOCIATIONS"] = int(len(sq))
        record["N_GTEX_SQTL_TISSUES"] = int(sq["GTEX_TISSUE"].nunique()) if not sq.empty else 0
        record["GTEX_SQTL_TISSUES"] = collapse(sq["GTEX_TISSUE"]) if not sq.empty else ""
        record["GTEX_SQTL_GENES"] = collapse(sq["GTEX_GENE_ID"]) if not sq.empty else ""
        record["GTEX_SQTL_PHENOTYPES"] = collapse(sq["GTEX_PHENOTYPE_ID"]) if not sq.empty else ""
        record["MIN_GTEX_SQTL_P"] = safe_numeric_min(sq["GTEX_PVALUE"]) if not sq.empty else np.nan
        record["MAX_ABS_GTEX_SQTL_NES"] = safe_numeric_max_abs(sq["GTEX_NES"]) if not sq.empty else np.nan

        record["HAS_GTEX_EQTL_OR_SQTL"] = (not eq.empty) or (not sq.empty)
        record["HAS_GTEX_EQTL_AND_SQTL"] = (not eq.empty) and (not sq.empty)

        top_eq = top_qtl_record(eq)
        top_sq = top_qtl_record(sq)
        record["TOP_EQTL_TISSUE"] = top_eq.get("GTEX_TISSUE", "")
        record["TOP_EQTL_GENE"] = top_eq.get("GTEX_GENE_ID", "")
        record["TOP_EQTL_P"] = top_eq.get("GTEX_PVALUE", np.nan)
        record["TOP_EQTL_NES"] = top_eq.get("GTEX_NES", np.nan)
        record["TOP_SQTL_TISSUE"] = top_sq.get("GTEX_TISSUE", "")
        record["TOP_SQTL_GENE"] = top_sq.get("GTEX_GENE_ID", "")
        record["TOP_SQTL_PHENOTYPE"] = top_sq.get("GTEX_PHENOTYPE_ID", "")
        record["TOP_SQTL_P"] = top_sq.get("GTEX_PVALUE", np.nan)
        record["TOP_SQTL_NES"] = top_sq.get("GTEX_NES", np.nan)
        rows.append(record)

    return pd.DataFrame(rows)


def build_locus_summary(summary: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for locus, group in summary.groupby("LOCUS_ID", dropna=False):
        eq = group[group["HAS_GTEX_EQTL"]]
        sq = group[group["HAS_GTEX_SQTL"]]
        any_qtl = group[group["HAS_GTEX_EQTL_OR_SQTL"]]
        rows.append(
            {
                "LOCUS_ID": locus,
                "N_VARIANTS": int(len(group)),
                "MAX_PIP": pd.to_numeric(group["PIP"], errors="coerce").max(),
                "N_EQTL_VARIANTS": int(len(eq)),
                "N_SQTL_VARIANTS": int(len(sq)),
                "N_ANY_QTL_VARIANTS": int(len(any_qtl)),
                "N_EQTL_AND_SQTL_VARIANTS": int(group["HAS_GTEX_EQTL_AND_SQTL"].sum()),
                "EQTL_TISSUES": collapse(eq["GTEX_EQTL_TISSUES"]) if not eq.empty else "",
                "SQTL_TISSUES": collapse(sq["GTEX_SQTL_TISSUES"]) if not sq.empty else "",
                "EQTL_GENES": collapse(eq["GTEX_EQTL_GENES"]) if not eq.empty else "",
                "SQTL_GENES": collapse(sq["GTEX_SQTL_GENES"]) if not sq.empty else "",
                "MIN_EQTL_P": safe_numeric_min(eq["MIN_GTEX_EQTL_P"]) if not eq.empty else np.nan,
                "MIN_SQTL_P": safe_numeric_min(sq["MIN_GTEX_SQTL_P"]) if not sq.empty else np.nan,
            }
        )
    return pd.DataFrame(rows)


# =============================================================================
# WORKER
# =============================================================================

def worker_mode() -> None:
    task_value = os.environ.get("SLURM_ARRAY_TASK_ID")
    manifest_value = os.environ.get("GWAS_QTL_MANIFEST")
    if not task_value:
        raise RuntimeError("SLURM_ARRAY_TASK_ID is not defined")
    if not manifest_value:
        raise RuntimeError("GWAS_QTL_MANIFEST is not defined")

    task_id = int(task_value)
    manifest_file = Path(manifest_value).resolve()
    if not manifest_file.exists():
        raise FileNotFoundError(f"QTL manifest not found: {manifest_file}")

    manifest = pd.read_csv(manifest_file, sep="\t", dtype=str, low_memory=False)
    required = [
        "QTL_TASK_ID",
        "STUDY_ACCESSION",
        "PHENOTYPE",
        "ANCESTRY_CODE",
        "ANCESTRY_LABEL",
        "STEP07_VARIANT_FILE",
        "OUTPUT_DIR",
        "GTEX_ROOT",
        "GTEX_EQTL_ROOT",
        "GTEX_SQTL_ROOT",
        "GTEX_LOOKUP_FILE",
        "CHUNK_SIZE",
    ]
    missing = [c for c in required if c not in manifest.columns]
    if missing:
        raise RuntimeError(f"QTL manifest is missing required columns: {missing}")

    task_numbers = pd.to_numeric(manifest["QTL_TASK_ID"], errors="coerce")
    selected = manifest.loc[task_numbers == task_id]
    if len(selected) != 1:
        raise RuntimeError(
            f"Expected exactly one QTL manifest row for task {task_id}; found {len(selected)}"
        )

    row = selected.iloc[0]
    accession = str(row["STUDY_ACCESSION"]).strip()
    phenotype = str(row["PHENOTYPE"]).strip()
    ancestry_code = str(row["ANCESTRY_CODE"]).strip().upper()
    ancestry_label = str(row["ANCESTRY_LABEL"]).strip()
    input_file = Path(row["STEP07_VARIANT_FILE"]).resolve()
    output_dir = Path(row["OUTPUT_DIR"]).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    force = str(row.get("FORCE", "False")).lower() in {"true", "1", "yes", "y"}
    force = force or os.environ.get("STEP08_FORCE", "0") == "1"
    rebuild_cache = str(row.get("REBUILD_CACHE", "False")).lower() in {"true", "1", "yes", "y"}
    rebuild_cache = rebuild_cache or os.environ.get("STEP08_REBUILD_CACHE", "0") == "1"

    mapping_output = output_dir / f"{accession}_GTEx_variant_mapping.tsv"
    eqtl_output = output_dir / f"{accession}_GTEx_eQTL.tsv.gz"
    sqtl_output = output_dir / f"{accession}_GTEx_sQTL.tsv.gz"
    gene_output = output_dir / f"{accession}_GTEx_variant_gene_evidence.tsv.gz"
    variant_output = output_dir / f"{accession}_GTEx_QTL_variant_summary.tsv"
    locus_output = output_dir / f"{accession}_GTEx_QTL_locus_summary.tsv"
    summary_output = output_dir / "qtl_summary.json"
    failed_output = output_dir / "QTL_FAILED.txt"

    if (
        not force
        and variant_output.exists()
        and variant_output.stat().st_size > 0
        and summary_output.exists()
        and summary_output.stat().st_size > 0
        and not failed_output.exists()
    ):
        banner("STEP 08 ALREADY COMPLETE")
        print(f"Study: {accession}")
        print(f"Output: {output_dir}")
        return

    banner("STEP 08 - GTEx v11 ALL-TISSUE QTL WORKER")
    print(f"Task       : {task_id}")
    print(f"Study      : {accession}")
    print(f"Phenotype  : {phenotype}")
    print(f"Ancestry   : {ancestry_label} ({ancestry_code})")
    print(f"Input      : {input_file}")
    print(f"GTEx       : {row['GTEX_ROOT']}")
    print("Tissues    : ALL GTEx v11 tissues")
    print(f"Output     : {output_dir}")

    try:
        if not input_file.exists() or input_file.stat().st_size == 0:
            raise FileNotFoundError(f"Step07 variant file missing/empty: {input_file}")

        # qtl_root is the parent containing all study dirs + shared cache.
        qtl_root = output_dir.parent
        cache = ensure_shared_cache(
            manifest=manifest,
            qtl_root=qtl_root,
            force_rebuild=rebuild_cache,
        )

        variants = load_step07_variants(input_file)
        variants["STUDY_ACCESSION"] = accession
        variants["PHENOTYPE"] = phenotype
        variants["ANCESTRY_CODE"] = ancestry_code
        variants["ANCESTRY_LABEL"] = ancestry_label

        shared_mapping = pd.read_csv(cache["mapping"], sep="\t", compression="gzip", low_memory=False)
        variants = variants.merge(
            shared_mapping[
                [
                    "GTEX_MATCH_KEY",
                    "GTEX_VARIANT_ID",
                    "GTEX_SNP_ID",
                    "GTEX_MAPPING_METHOD",
                ]
            ],
            on="GTEX_MATCH_KEY",
            how="left",
            validate="many_to_one",
        )
        variants["GTEX_VARIANT_ID"] = variants["GTEX_VARIANT_ID"].fillna(
            variants["GTEX_CONSTRUCTED_VARIANT_ID"]
        )
        variants.to_csv(mapping_output, sep="\t", index=False)

        study_ids = set(variants["GTEX_VARIANT_ID"].dropna().astype(str))
        study_ids.update(variants["GTEX_CONSTRUCTED_VARIANT_ID"].dropna().astype(str))

        shared_eqtl = pd.read_csv(cache["eqtl"], sep="\t", compression="gzip", low_memory=False)
        shared_sqtl = pd.read_csv(cache["sqtl"], sep="\t", compression="gzip", low_memory=False)

        eqtl_raw = shared_eqtl[shared_eqtl["GTEX_VARIANT_ID"].astype(str).isin(study_ids)].copy()
        sqtl_raw = shared_sqtl[shared_sqtl["GTEX_VARIANT_ID"].astype(str).isin(study_ids)].copy()

        eqtl = add_variant_context(eqtl_raw, variants)
        sqtl = add_variant_context(sqtl_raw, variants)

        eqtl.to_csv(eqtl_output, sep="\t", index=False, compression="gzip")
        sqtl.to_csv(sqtl_output, sep="\t", index=False, compression="gzip")

        gene_evidence = make_variant_gene_evidence(eqtl, sqtl)
        gene_evidence.to_csv(gene_output, sep="\t", index=False, compression="gzip")

        variant_summary = build_variant_summary(variants, eqtl, sqtl)
        variant_summary.to_csv(variant_output, sep="\t", index=False)

        locus_summary = build_locus_summary(variant_summary)
        locus_summary.to_csv(locus_output, sep="\t", index=False)

        n_total = int(len(variant_summary))
        n_eqtl = int(variant_summary["HAS_GTEX_EQTL"].sum())
        n_sqtl = int(variant_summary["HAS_GTEX_SQTL"].sum())
        n_both = int(variant_summary["HAS_GTEX_EQTL_AND_SQTL"].sum())
        n_any = int(variant_summary["HAS_GTEX_EQTL_OR_SQTL"].sum())
        n_none = int(n_total - n_any)

        summary = {
            "STEP08_VERSION": STEP08_VERSION,
            "QTL_TASK_ID": task_id,
            "STUDY_ACCESSION": accession,
            "PHENOTYPE": phenotype,
            "ANCESTRY_CODE": ancestry_code,
            "ANCESTRY_LABEL": ancestry_label,
            "GTEX_RELEASE": "v11",
            "GENOME_BUILD": "GRCh38",
            "TISSUE_POLICY": "ALL_GTEX_V11_TISSUES",
            "N_INPUT_VARIANTS": n_total,
            "N_EQTL_VARIANTS": n_eqtl,
            "N_SQTL_VARIANTS": n_sqtl,
            "N_EQTL_AND_SQTL_VARIANTS": n_both,
            "N_ANY_QTL_VARIANTS": n_any,
            "N_NO_SIGNIFICANT_QTL_VARIANTS": n_none,
            "N_EQTL_ASSOCIATIONS": int(len(eqtl)),
            "N_SQTL_ASSOCIATIONS": int(len(sqtl)),
            "N_VARIANT_GENE_EVIDENCE_ROWS": int(len(gene_evidence)),
            "N_LOCI": int(variant_summary["LOCUS_ID"].nunique()),
            "N_EQTL_TISSUES_WITH_MATCHES": int(eqtl["GTEX_TISSUE"].nunique()) if not eqtl.empty else 0,
            "N_SQTL_TISSUES_WITH_MATCHES": int(sqtl["GTEX_TISSUE"].nunique()) if not sqtl.empty else 0,
            "VARIANT_MAPPING_FILE": str(mapping_output),
            "EQTL_FILE": str(eqtl_output),
            "SQTL_FILE": str(sqtl_output),
            "VARIANT_GENE_EVIDENCE_FILE": str(gene_output),
            "VARIANT_SUMMARY_FILE": str(variant_output),
            "LOCUS_SUMMARY_FILE": str(locus_output),
            "STATUS": "COMPLETE",
            "COMPLETED_UTC": datetime.now(timezone.utc).isoformat(),
        }
        write_json(summary_output, summary)

        if failed_output.exists():
            failed_output.unlink()

        banner("STEP 08 COMPLETE")
        print(f"Study                     : {accession}")
        print(f"Input variants            : {n_total:,}")
        print(f"eQTL variants             : {n_eqtl:,}")
        print(f"sQTL variants             : {n_sqtl:,}")
        print(f"Both eQTL + sQTL          : {n_both:,}")
        print(f"Any significant GTEx QTL  : {n_any:,}")
        print(f"No significant GTEx QTL   : {n_none:,}")
        print(f"eQTL associations         : {len(eqtl):,}")
        print(f"sQTL associations         : {len(sqtl):,}")
        print(f"Loci                      : {variant_summary['LOCUS_ID'].nunique():,}")
        print(f"Main table                : {variant_output}")

    except Exception as error:
        failure_text = (
            "STEP 08 GTEx QTL INTEGRATION FAILED\n\n"
            f"Task ID: {task_id}\n"
            f"Accession: {accession}\n"
            f"Phenotype: {phenotype}\n"
            f"Ancestry: {ancestry_label} ({ancestry_code})\n"
            f"Input: {input_file}\n\n"
            f"Error:\n{type(error).__name__}: {error}\n\n"
            f"{traceback.format_exc()}"
        )
        failed_output.write_text(failure_text, encoding="utf-8")
        print(failure_text, file=sys.stderr)
        raise


# =============================================================================
# DIRECT INDEX MODE
# =============================================================================

def direct_index_mode(args) -> None:
    validate_arguments(args)
    root = Path.cwd().resolve()
    phenotype = args.phenotype.strip()
    phenotype_slug = slugify(phenotype)
    ancestry_code, ancestry_label = canonical_ancestry(args.ancestry)
    ancestry_slug = slugify(ancestry_label)

    manifest_file = (
        root / "08_qtl" / phenotype_slug / ancestry_slug / "qtl_manifest.tsv"
    ).resolve()

    if not manifest_file.exists():
        raise FileNotFoundError(
            "Step08 manifest does not exist. Run the planner once without --index first:\n\n"
            f"  python {Path(__file__).name} --phenotype {shlex.quote(phenotype)} "
            f"--ancestry {shlex.quote(ancestry_code)}"
        )

    manifest = pd.read_csv(manifest_file, sep="\t", dtype=str, low_memory=False)
    if "QTL_TASK_ID" not in manifest.columns:
        raise RuntimeError("Step08 manifest has no QTL_TASK_ID column")
    task_numbers = pd.to_numeric(manifest["QTL_TASK_ID"], errors="coerce")
    selected = manifest.loc[task_numbers == args.index]
    if len(selected) != 1:
        available = [int(x) for x in task_numbers.dropna()]
        raise RuntimeError(
            f"Index {args.index} is not present exactly once. Available: {available}"
        )

    row = selected.iloc[0]
    banner("STEP 08 - DIRECT SINGLE-INDEX MODE")
    print(f"Manifest : {manifest_file}")
    print(f"Index    : {args.index}")
    print(f"Study    : {row['STUDY_ACCESSION']}")
    print("Tissues  : ALL GTEx v11 tissues")
    print()
    print(
        "NOTE: the first run can scan several GB of GTEx data. On HPC use srun "
        "or submit the generated SLURM array rather than doing heavy work on a login node."
    )

    old_values = {
        key: os.environ.get(key)
        for key in [
            "SLURM_ARRAY_TASK_ID",
            "GWAS_QTL_MANIFEST",
            "SLURM_CPUS_PER_TASK",
            "STEP08_FORCE",
            "STEP08_REBUILD_CACHE",
        ]
    }

    try:
        os.environ["SLURM_ARRAY_TASK_ID"] = str(args.index)
        os.environ["GWAS_QTL_MANIFEST"] = str(manifest_file)
        os.environ["SLURM_CPUS_PER_TASK"] = str(args.cpus)
        if args.force:
            os.environ["STEP08_FORCE"] = "1"
        if args.rebuild_cache:
            os.environ["STEP08_REBUILD_CACHE"] = "1"
        worker_mode()
    finally:
        for key, value in old_values.items():
            if value is None:
                os.environ.pop(key, None)
            else:
                os.environ[key] = value


# =============================================================================
# MAIN
# =============================================================================

def main() -> None:
    if os.environ.get("SLURM_ARRAY_TASK_ID") and os.environ.get("GWAS_QTL_MANIFEST"):
        worker_mode()
        return

    args = arguments()
    if args.index is not None:
        direct_index_mode(args)
    else:
        planner_mode(args)


if __name__ == "__main__":
    main()
