#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
================================================================================
GWAS2m STEP 12
INTEGRATED LOCUS -> GENE -> MECHANISM MASTER TABLE
================================================================================

PURPOSE
-------
Step12 integrates GWAS2m's own evidence AFTER strict Step11 molecular-QTL
colocalisation. It does NOT use Open Targets. Open Targets must remain an
independent downstream benchmark.

Evidence integrated per phenotype / ancestry:
    Step06  fine-mapping: loci, variants, PIP, 95% credible-set membership
    Step07  VEP annotation: genes, consequences, impact, functional category
    Step08  descriptive GTEx v11 eQTL/sQTL overlaps (carried downstream)
    Step09  SpliceAI predictions
    Step10  Pangolin + integrated splice evidence
    Step11  strict formal coloc.susie results:
            eQTL / sQTL / pQTL / caQTL / other configured molecular-QTLs

MAIN SCIENTIFIC OUTPUTS
-----------------------
1. Variant evidence table
2. Formal molecular-QTL colocalisation table
3. Locus x gene evidence table
4. Ranked/prioritised genes per locus
5. Final locus -> mechanism summary (printed to screen AND saved)
6. Unresolved loci (do not force a gene)
7. Phenotype-level consensus loci across studies
8. Unique prioritised-gene list for Step13 pathway/network analysis

IMPORTANT RULES
---------------
* Missing data/resource errors are never converted into biological negatives.
* Step11 formal evidence counts only rows with COLOC_TESTED=YES and STATUS=COMPLETE.
* eQTL, sQTL, pQTL and caQTL remain separate evidence modalities.
* Gene ranking is internal to GWAS2m; Open Targets is NOT used here.
* Rankings are transparent/lexicographic, not a black-box ML score.
* Non-coding loci without a defensible gene link remain UNRESOLVED.
* A caQTL peak with no target gene is retained as a regulatory mechanism, not
  forcibly assigned to the nearest gene.

RUN
---
    python Step12_Build_Locus_Mechanisms.py \
        --phenotype "parkinson's disease" \
        --ancestry EUR

Single study:
    python Step12_Build_Locus_Mechanisms.py \
        --phenotype "parkinson's disease" \
        --ancestry EUR \
        --study GCST90473307

Allow incomplete/failed Step11 loci for exploratory inspection only:
    python Step12_Build_Locus_Mechanisms.py \
        --phenotype "parkinson's disease" \
        --ancestry EUR \
        --allow-incomplete-step11

OUTPUT
------
12_locus_mechanisms/<phenotype>/<ancestry>/
    all_variant_evidence.tsv.gz
    formal_coloc_all.tsv
    all_gene_evidence.tsv
    prioritized_genes.tsv
    locus_mechanism_summary.tsv
    unresolved_loci.tsv
    phenotype_consensus_loci.tsv
    pathway_input_genes.tsv
    step12_input_audit.tsv
    step12_summary.json

================================================================================
"""

from __future__ import annotations

import argparse
import json
import math
import re
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

import numpy as np
import pandas as pd


STEP12_VERSION = "1.0.0"

ANCESTRY = {
    "eur": ("EUR", "European"),
    "european": ("EUR", "European"),
    "afr": ("AFR", "African"),
    "african": ("AFR", "African"),
    "eas": ("EAS", "East Asian"),
    "east asian": ("EAS", "East Asian"),
    "sas": ("SAS", "South Asian"),
    "south asian": ("SAS", "South Asian"),
    "amr": ("AMR", "Hispanic or Latin American"),
    "hispanic": ("AMR", "Hispanic or Latin American"),
    "latino": ("AMR", "Hispanic or Latin American"),
    "hispanic or latin american": ("AMR", "Hispanic or Latin American"),
}

# VEP functional categories generated by Step07, from strongest to weakest
FUNCTIONAL_CATEGORY_RANK = {
    "SPLICING": 0,
    "CODING": 1,
    "UTR": 2,
    "REGULATORY": 3,
    "NONCODING_RNA": 4,
    "INTRONIC": 5,
    "UPSTREAM": 6,
    "DOWNSTREAM": 7,
    "INTERGENIC": 8,
    "OTHER": 9,
    "": 99,
}

IMPACT_RANK = {
    "HIGH": 0,
    "MODERATE": 1,
    "LOW": 2,
    "MODIFIER": 3,
    "": 99,
}

TIER_RANK = {
    "TIER1_HIGH": 1,
    "TIER2_MODERATE": 2,
    "TIER3_SUPPORTING": 3,
    "TIER4_WEAK": 4,
    "UNRESOLVED": 9,
}

DEFAULT_STRONG_PP4 = 0.80
DEFAULT_SUGGESTIVE_PP4 = 0.50
DEFAULT_MIN_PATHWAY_TIER = 2


# =============================================================================
# GENERIC HELPERS
# =============================================================================

def utcnow() -> str:
    return datetime.now(timezone.utc).isoformat()


def banner(text: str) -> None:
    print()
    print("=" * 150)
    print(text)
    print("=" * 150)


def normalize_text(value) -> str:
    x = str(value).strip().lower()
    x = re.sub(r"[^a-z0-9]+", " ", x)
    x = re.sub(r"\s+", " ", x)
    return x.strip()


def slugify(value) -> str:
    return normalize_text(value).replace(" ", "_")


def canonical_ancestry(value: str) -> tuple[str, str]:
    key = normalize_text(value)
    if key not in ANCESTRY:
        raise SystemExit(
            f"Unsupported ancestry: {value!r}. Use EUR/AFR/EAS/SAS/AMR "
            "or the corresponding full label."
        )
    return ANCESTRY[key]


def canonical_chr(value) -> str:
    if value is None or pd.isna(value):
        return ""
    x = str(value).strip()
    x = re.sub(r"^chr", "", x, flags=re.I)
    if x.endswith(".0"):
        x = x[:-2]
    return x.upper()


def safe_numeric(value):
    return pd.to_numeric(value, errors="coerce")


def safe_int0(value) -> int:
    if value is None:
        return 0
    try:
        if pd.isna(value):
            return 0
    except Exception:
        pass
    try:
        number = float(value)
    except (TypeError, ValueError):
        return 0
    if not np.isfinite(number):
        return 0
    return int(number)


def boolish(value) -> bool:
    if isinstance(value, (bool, np.bool_)):
        return bool(value)
    if value is None:
        return False
    return str(value).strip().lower() in {
        "1", "true", "t", "yes", "y", "on",
    }


def bool_series(series: pd.Series) -> pd.Series:
    return series.map(boolish).fillna(False).astype(bool)


def split_tokens(value) -> list[str]:
    if value is None:
        return []
    try:
        if pd.isna(value):
            return []
    except Exception:
        pass
    x = str(value).strip()
    if not x or x.lower() in {"nan", "none", "na", "null", "."}:
        return []
    parts = re.split(r"[;,|]", x)
    out = []
    for token in parts:
        token = token.strip()
        if token and token not in out:
            out.append(token)
    return out


def join_unique(values: Iterable) -> str:
    out: list[str] = []
    for value in values:
        for token in split_tokens(value):
            if token not in out:
                out.append(token)
    return ";".join(out)


def first_nonempty(values: Iterable, default=""):
    for value in values:
        if value is None:
            continue
        try:
            if pd.isna(value):
                continue
        except Exception:
            pass
        x = str(value).strip()
        if x and x.lower() not in {"nan", "none", "na", "null", "."}:
            return value
    return default


def read_table(path: Path | None, required: bool = False) -> pd.DataFrame:
    if path is None or not path.exists() or path.stat().st_size == 0:
        if required:
            raise FileNotFoundError(f"Missing/empty required table: {path}")
        return pd.DataFrame()
    try:
        return pd.read_csv(path, sep="\t", compression="infer", low_memory=False)
    except pd.errors.EmptyDataError:
        if required:
            raise RuntimeError(f"Required table has no columns: {path}")
        return pd.DataFrame()


def safe_json(path: Path | None) -> dict:
    if path is None or not path.exists() or path.stat().st_size == 0:
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


def write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(payload, indent=2, sort_keys=True, default=json_safe),
        encoding="utf-8",
    )


def json_safe(obj):
    if isinstance(obj, (np.integer,)):
        return int(obj)
    if isinstance(obj, (np.floating,)):
        return None if np.isnan(obj) else float(obj)
    if isinstance(obj, (np.bool_,)):
        return bool(obj)
    if isinstance(obj, Path):
        return str(obj)
    if isinstance(obj, np.ndarray):
        return obj.tolist()
    try:
        if pd.isna(obj):
            return None
    except Exception:
        pass
    raise TypeError(f"Not JSON serialisable: {type(obj).__name__}")


def first_existing(base: Path, patterns: list[str]) -> Path | None:
    for pattern in patterns:
        if any(ch in pattern for ch in "*?[]"):
            hits = sorted(base.glob(pattern)) if base.exists() else []
            for hit in hits:
                if hit.exists() and hit.stat().st_size > 0:
                    return hit
        else:
            hit = base / pattern
            if hit.exists() and hit.stat().st_size > 0:
                return hit
    return None


def gene_base(value) -> str:
    if value is None:
        return ""
    try:
        if pd.isna(value):
            return ""
    except Exception:
        pass
    x = str(value).strip()
    if not x or x.lower() in {"nan", "none", "na", "null", "."}:
        return ""
    match = re.search(r"(ENSG\d+)", x, re.I)
    if match:
        return match.group(1).upper()
    return x


def canonical_variant_from_row(row: pd.Series) -> str:
    chrom = canonical_chr(
        first_nonempty([
            row.get("CHR"), row.get("CHROM"), row.get("chromosome"),
            row.get("PANGOLIN_CHROM"),
        ])
    )
    pos = first_nonempty([
        row.get("REFERENCE_POS"), row.get("POS"), row.get("position"),
        row.get("PANGOLIN_POS"),
    ], default=np.nan)
    ref = str(first_nonempty([
        row.get("REFERENCE_REF"), row.get("REF"), row.get("ref"),
        row.get("PANGOLIN_REF"),
    ])).upper().strip()
    alt = str(first_nonempty([
        row.get("REFERENCE_ALT"), row.get("ALT"), row.get("alt"),
        row.get("PANGOLIN_ALT"),
    ])).upper().strip()
    try:
        pos = int(float(pos))
    except Exception:
        return str(first_nonempty([row.get("REFERENCE_ID"), row.get("SNPID"), row.get("rsID")]))
    if not chrom or not ref or not alt:
        return str(first_nonempty([row.get("REFERENCE_ID"), row.get("SNPID"), row.get("rsID")]))
    return f"{chrom}:{pos}:{ref}:{alt}"


def show(df: pd.DataFrame, title: str, columns: list[str] | None = None,
         max_rows: int | None = None) -> None:
    banner(title)
    if df is None or df.empty:
        print("(no rows)")
        return
    x = df.copy()
    if columns:
        columns = [c for c in columns if c in x.columns]
        x = x[columns]
    if max_rows is not None:
        x = x.head(max_rows)
    with pd.option_context(
        "display.max_rows", None,
        "display.max_columns", None,
        "display.width", 500,
        "display.max_colwidth", 55,
        "display.expand_frame_repr", False,
        "display.float_format", lambda v: f"{v:.4g}",
    ):
        print(x.to_string(index=False))


# =============================================================================
# PATHS / INPUT DISCOVERY
# =============================================================================

def make_paths(root: Path, phenotype: str, ancestry_label: str) -> dict[str, Path]:
    p = slugify(phenotype)
    a = slugify(ancestry_label)
    return {
        "S06": root / "06_finemapping" / p / a,
        "S07": root / "07_annotation" / p / a,
        "S08": root / "08_qtl" / p / a,
        "S09": root / "09_splicing" / p / a,
        "S10": root / "10_pangolin" / p / a,
        "S11": root / "11_coloc_formal" / p / a,
        "OUT": root / "12_locus_mechanisms" / p / a,
    }


def discover_studies(paths: dict[str, Path], study: str | None) -> list[str]:
    """Return only studies selected by strict Step11.

    Step12 runs after Step11, therefore coloc_manifest.tsv defines the
    authoritative phenotype/study/locus universe. Historical Step06-Step10
    directories must not re-introduce studies excluded before formal coloc.
    """
    manifest = paths["S11"] / "coloc_manifest.tsv"
    studies = set()

    if manifest.exists() and manifest.stat().st_size > 0:
        try:
            m = pd.read_csv(
                manifest,
                sep="\t",
                dtype=str,
                low_memory=False,
            )
        except pd.errors.EmptyDataError:
            m = pd.DataFrame()

        if not m.empty and "STUDY_ACCESSION" in m.columns:
            studies = {
                str(x).strip()
                for x in m["STUDY_ACCESSION"].dropna()
                if re.fullmatch(r"GCST\d+", str(x).strip())
            }

    # Legacy fallback: only genuine Step11 study output directories.
    if not studies and paths["S11"].exists():
        for child in paths["S11"].glob("GCST*"):
            if (
                child.is_dir()
                and re.fullmatch(r"GCST\d+", child.name)
                and (child / "loci").exists()
            ):
                studies.add(child.name)

    if study:
        requested = str(study).strip()
        studies = {x for x in studies if x == requested}

    return sorted(studies)


def study_files(paths: dict[str, Path], accession: str) -> dict[str, Path | None]:
    s06 = paths["S06"] / accession
    s07 = paths["S07"] / accession
    s08 = paths["S08"] / accession
    s09 = paths["S09"] / accession
    s10 = paths["S10"] / accession
    s11 = paths["S11"] / accession

    return {
        "S06_LOCI": s06 / "loci_definition.tsv",
        "S06_VARIANTS": first_existing(s06, [
            f"{accession}_finemapped_variants.tsv.gz",
            f"{accession}_finemapped_variants.tsv",
        ]),
        "S07_VARIANTS": first_existing(s07, [
            f"{accession}_VEP_variant_summary.tsv",
            f"{accession}_VEP_best_consequence.tsv",
        ]),
        "S08_VARIANTS": first_existing(s08, [
            f"{accession}_GTEx_QTL_variant_summary.tsv",
        ]),
        "S09_VARIANTS": first_existing(s09, [
            f"{accession}_SpliceAI_variant_summary.tsv",
        ]),
        "S10_VARIANTS": first_existing(s10, [
            f"{accession}_SpliceAI_Pangolin_integrated.tsv",
            f"{accession}_Pangolin_variant_summary.tsv",
        ]),
        "S11_SUMMARY": s11 / "coloc_summary.json",
        "S11_ROOT": s11,
    }


# =============================================================================
# STEP11 STRICT COMPLETENESS / COLOC LOADING
# =============================================================================

def step11_locus_statuses(paths: dict[str, Path], accession: str) -> pd.DataFrame:
    root = paths["S11"] / accession / "loci"
    rows = []
    if not root.exists():
        return pd.DataFrame(columns=[
            "STUDY_ACCESSION", "LOCUS_ID", "STATUS", "N_CANDIDATES",
            "N_TESTED", "N_RESOURCE_ERRORS", "N_RESOURCE_UNAVAILABLE",
        ])
    for locus_dir in sorted(root.glob("L*")):
        if not locus_dir.is_dir():
            continue
        meta = safe_json(locus_dir / "locus_summary.json")
        rows.append({
            "STUDY_ACCESSION": accession,
            "LOCUS_ID": locus_dir.name,
            "STATUS": str(meta.get("STATUS", "MISSING")),
            "N_CANDIDATES": meta.get("N_CANDIDATES", np.nan),
            "N_TESTED": meta.get("N_TESTED", np.nan),
            "N_RESOURCE_ERRORS": meta.get("N_RESOURCE_ERRORS", np.nan),
            "N_RESOURCE_UNAVAILABLE": meta.get("N_RESOURCE_UNAVAILABLE", np.nan),
            "ELAPSED_MINUTES": meta.get("ELAPSED_MINUTES", np.nan),
            "ERROR": meta.get("ERROR", ""),
        })
    return pd.DataFrame(rows)


def load_formal_coloc_for_study(paths: dict[str, Path], accession: str) -> pd.DataFrame:
    root = paths["S11"] / accession / "loci"
    frames = []
    if not root.exists():
        return pd.DataFrame()
    for locus_dir in sorted(root.glob("L*")):
        path = locus_dir / "locus_formal_coloc.tsv"
        x = read_table(path)
        if x.empty:
            continue
        if "STUDY_ACCESSION" not in x.columns:
            x["STUDY_ACCESSION"] = accession
        if "LOCUS_ID" not in x.columns:
            x["LOCUS_ID"] = locus_dir.name
        frames.append(x)
    if not frames:
        return pd.DataFrame()
    out = pd.concat(frames, ignore_index=True, sort=False)
    for c in [
        "MAX_PP_H0", "MAX_PP_H1", "MAX_PP_H2", "MAX_PP_H3", "MAX_PP_H4",
        "PP_H4_P12_LOW", "PP_H4_P12_DEFAULT", "PP_H4_P12_HIGH",
        "N_COMMON_SNPS", "DISCOVERY_MIN_P",
    ]:
        if c in out.columns:
            out[c] = pd.to_numeric(out[c], errors="coerce")
    return out


# =============================================================================
# VARIANT EVIDENCE LOADING
# =============================================================================

def prepare_variant_table(x: pd.DataFrame, accession: str, source: str) -> pd.DataFrame:
    if x.empty:
        return x
    x = x.copy()
    if "STUDY_ACCESSION" not in x.columns:
        x["STUDY_ACCESSION"] = accession
    x["STUDY_ACCESSION"] = accession
    x["VARIANT_SOURCE_TABLE"] = source
    if "LOCUS_ID" not in x.columns:
        x["LOCUS_ID"] = ""
    x["VARIANT_KEY"] = x.apply(canonical_variant_from_row, axis=1)
    if "PIP" in x.columns:
        x["PIP"] = pd.to_numeric(x["PIP"], errors="coerce")
    if "SPLICEAI_MAX_DS" in x.columns:
        x["SPLICEAI_MAX_DS"] = pd.to_numeric(x["SPLICEAI_MAX_DS"], errors="coerce")
    if "PANGOLIN_MAX_ABS" in x.columns:
        x["PANGOLIN_MAX_ABS"] = pd.to_numeric(x["PANGOLIN_MAX_ABS"], errors="coerce")
    return x


def load_best_variant_table(files: dict[str, Path | None], accession: str) -> tuple[pd.DataFrame, str]:
    # Richest downstream table first. Step10's integrated table carries Step09,
    # which carries Step08, which carries Step07/VEP + fine-mapping evidence.
    choices = [
        ("STEP10_INTEGRATED", files["S10_VARIANTS"]),
        ("STEP09_SPLICEAI", files["S09_VARIANTS"]),
        ("STEP08_QTL", files["S08_VARIANTS"]),
        ("STEP07_VEP", files["S07_VARIANTS"]),
        ("STEP06_FINEMAP", files["S06_VARIANTS"]),
    ]
    for label, path in choices:
        x = read_table(path)
        if not x.empty:
            return prepare_variant_table(x, accession, label), label
    return pd.DataFrame(), "MISSING"


# =============================================================================
# GENE MAPPING FROM VARIANT EVIDENCE
# =============================================================================

def build_ensembl_symbol_maps(variants: pd.DataFrame) -> tuple[dict[str, str], dict[str, str]]:
    ens_to_symbol: dict[str, str] = {}
    symbol_to_ens: dict[str, str] = {}
    if variants.empty:
        return ens_to_symbol, symbol_to_ens
    for _, row in variants.iterrows():
        ens = gene_base(row.get("Gene", ""))
        symbol = str(row.get("SYMBOL", "")).strip()
        if ens.startswith("ENSG") and symbol:
            ens_to_symbol.setdefault(ens, symbol)
            symbol_to_ens.setdefault(symbol.upper(), ens)
    return ens_to_symbol, symbol_to_ens


def canonical_gene_key(token: str, symbol_to_ens: dict[str, str]) -> tuple[str, str, str]:
    token = str(token).strip()
    if not token:
        return "", "", ""
    base = gene_base(token)
    if base.startswith("ENSG"):
        return base, base, ""
    symbol = token
    ens = symbol_to_ens.get(symbol.upper(), "")
    if ens:
        return ens, ens, symbol
    return symbol.upper(), "", symbol


def variant_gene_links(variants: pd.DataFrame) -> pd.DataFrame:
    if variants.empty:
        return pd.DataFrame()

    ens_to_symbol, symbol_to_ens = build_ensembl_symbol_maps(variants)
    rows = []

    for _, row in variants.iterrows():
        base_info = {
            "STUDY_ACCESSION": row.get("STUDY_ACCESSION", ""),
            "LOCUS_ID": row.get("LOCUS_ID", ""),
            "VARIANT_KEY": row.get("VARIANT_KEY", ""),
            "REFERENCE_ID": row.get("REFERENCE_ID", row.get("SNPID", row.get("rsID", ""))),
            "PIP": row.get("PIP", np.nan),
            "IN_95_CREDIBLE_SET": boolish(
                row.get("IN_95_CREDIBLE_SET", row.get("SELECTED_CREDIBLE_SET", False))
            ),
            "FUNCTIONAL_CATEGORY": str(row.get("FUNCTIONAL_CATEGORY", "")).upper(),
            "IMPACT": str(row.get("IMPACT", "")).upper(),
            "CONSEQUENCE": row.get("Consequence", row.get("ALL_CONSEQUENCES", "")),
            "SPLICEAI_MAX_DS": row.get("SPLICEAI_MAX_DS", np.nan),
            "PANGOLIN_MAX_ABS": row.get("PANGOLIN_MAX_ABS", np.nan),
            "PANGOLIN_TOP_5PCT": boolish(row.get("PANGOLIN_TOP_5PCT", False)),
            "N_SPLICE_EVIDENCE_SOURCES": row.get("N_SPLICE_EVIDENCE_SOURCES", 0),
            "SPLICE_EVIDENCE_CLASS": row.get("SPLICE_EVIDENCE_CLASS", ""),
        }

        candidates: list[tuple[str, str]] = []

        # Direct VEP transcript-level mapping is the cleanest annotation link.
        direct_ens = gene_base(row.get("Gene", ""))
        direct_symbol = str(row.get("SYMBOL", "")).strip()
        if direct_ens or direct_symbol:
            token = direct_ens if direct_ens else direct_symbol
            candidates.append((token, "VEP"))
            if direct_ens.startswith("ENSG") and direct_symbol:
                ens_to_symbol.setdefault(direct_ens, direct_symbol)
                symbol_to_ens.setdefault(direct_symbol.upper(), direct_ens)

        for col, source in [
            ("ALL_SYMBOLS", "VEP_ALL_SYMBOLS"),
            ("SPLICEAI_GENE", "SPLICEAI"),
            ("SPLICEAI_ALL_GENES", "SPLICEAI"),
            ("PANGOLIN_GENE", "PANGOLIN"),
            ("PANGOLIN_ALL_GENES", "PANGOLIN"),
        ]:
            if col in row.index:
                for token in split_tokens(row.get(col, "")):
                    candidates.append((token, source))

        seen = set()
        for token, source in candidates:
            key, ens, symbol = canonical_gene_key(token, symbol_to_ens)
            if not key:
                continue
            if not symbol and ens:
                symbol = ens_to_symbol.get(ens, "")
            marker = (key, source)
            if marker in seen:
                continue
            seen.add(marker)
            rows.append({
                **base_info,
                "GENE_KEY": key,
                "GENE_ID": ens,
                "GENE_SYMBOL": symbol,
                "GENE_SOURCE": source,
            })

    return pd.DataFrame(rows)


def best_text_by_rank(group: pd.DataFrame, column: str, rank_map: dict[str, int]) -> str:
    if column not in group.columns or group.empty:
        return ""
    vals = group[column].fillna("").astype(str).str.upper()
    if vals.empty:
        return ""
    ranks = vals.map(rank_map).fillna(99)
    if ranks.empty:
        return ""
    idx = ranks.idxmin()
    return str(group.loc[idx, column])


def aggregate_variant_gene_evidence(links: pd.DataFrame) -> pd.DataFrame:
    if links.empty:
        return pd.DataFrame()
    rows = []
    for (study, locus, gene_key), g in links.groupby(
        ["STUDY_ACCESSION", "LOCUS_ID", "GENE_KEY"], dropna=False, sort=False
    ):
        pips = pd.to_numeric(g["PIP"], errors="coerce")
        sai = pd.to_numeric(g["SPLICEAI_MAX_DS"], errors="coerce")
        pang = pd.to_numeric(g["PANGOLIN_MAX_ABS"], errors="coerce")
        nsplice = pd.to_numeric(g["N_SPLICE_EVIDENCE_SOURCES"], errors="coerce")
        top_pip = pips.max() if pips.notna().any() else np.nan
        if pips.notna().any():
            top_idx = pips.idxmax()
            best_variant = str(g.loc[top_idx, "VARIANT_KEY"])
            best_reference_id = str(g.loc[top_idx, "REFERENCE_ID"])
        else:
            best_variant = str(first_nonempty(g["VARIANT_KEY"].tolist()))
            best_reference_id = str(first_nonempty(g["REFERENCE_ID"].tolist()))

        rows.append({
            "STUDY_ACCESSION": study,
            "LOCUS_ID": locus,
            "GENE_KEY": gene_key,
            "GENE_ID": str(first_nonempty(g["GENE_ID"].tolist())),
            "GENE_SYMBOL": str(first_nonempty(g["GENE_SYMBOL"].tolist())),
            "VARIANT_GENE_SOURCES": join_unique(g["GENE_SOURCE"]),
            "N_GENE_LINKED_VARIANTS": int(g["VARIANT_KEY"].replace("", np.nan).nunique()),
            "MAX_PIP": top_pip,
            "N_95CS_GENE_VARIANTS": int(bool_series(g["IN_95_CREDIBLE_SET"]).sum()),
            "BEST_VARIANT": best_variant,
            "BEST_REFERENCE_ID": best_reference_id,
            "BEST_FUNCTIONAL_CATEGORY": best_text_by_rank(
                g, "FUNCTIONAL_CATEGORY", FUNCTIONAL_CATEGORY_RANK
            ),
            "BEST_IMPACT": best_text_by_rank(g, "IMPACT", IMPACT_RANK),
            "CONSEQUENCES": join_unique(g["CONSEQUENCE"]),
            "MAX_SPLICEAI_DS": sai.max() if sai.notna().any() else np.nan,
            "MAX_PANGOLIN_ABS": pang.max() if pang.notna().any() else np.nan,
            "ANY_PANGOLIN_TOP5": bool(bool_series(g["PANGOLIN_TOP_5PCT"]).any()),
            "MAX_SPLICE_EVIDENCE_SOURCES": int(nsplice.max()) if nsplice.notna().any() else 0,
            "SPLICE_EVIDENCE_CLASSES": join_unique(g["SPLICE_EVIDENCE_CLASS"]),
        })
    return pd.DataFrame(rows)


# =============================================================================
# COLOC -> GENE EVIDENCE
# =============================================================================

def map_coloc_gene(row: pd.Series, ens_to_symbol: dict[str, str],
                   symbol_to_ens: dict[str, str]) -> tuple[str, str, str]:
    raw = str(row.get("GENE_ID", "")).strip()
    if not raw:
        # Some QTL sources place an Ensembl gene in the molecular trait identifier.
        trait = str(row.get("MOLECULAR_TRAIT_ID", ""))
        m = re.search(r"(ENSG\d+)", trait, re.I)
        if m:
            raw = m.group(1)
    if not raw:
        return "", "", ""
    base = gene_base(raw)
    if base.startswith("ENSG"):
        return base, base, ens_to_symbol.get(base, "")
    symbol = raw
    ens = symbol_to_ens.get(symbol.upper(), "")
    if ens:
        return ens, ens, symbol
    return symbol.upper(), "", symbol


def aggregate_coloc_gene_evidence(coloc: pd.DataFrame, variants: pd.DataFrame,
                                  strong_pp4: float,
                                  suggestive_pp4: float) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Return (gene-level formal evidence, locus-level QTL evidence)."""
    if coloc.empty:
        return pd.DataFrame(), pd.DataFrame()

    ens_to_symbol, symbol_to_ens = build_ensembl_symbol_maps(variants)
    x = coloc.copy()
    x["COLOC_TESTED_BOOL"] = x.get(
        "COLOC_TESTED", pd.Series("NO", index=x.index)
    ).astype(str).str.upper().eq("YES")
    x["STATUS_COMPLETE_BOOL"] = x.get(
        "STATUS", pd.Series("", index=x.index)
    ).astype(str).str.upper().eq("COMPLETE")
    x["FORMAL_VALID"] = x["COLOC_TESTED_BOOL"] & x["STATUS_COMPLETE_BOOL"]
    x["MAX_PP_H4"] = pd.to_numeric(x.get("MAX_PP_H4"), errors="coerce")
    x["MAX_PP_H3"] = pd.to_numeric(x.get("MAX_PP_H3"), errors="coerce")
    x["PRIOR_ROBUST_BOOL"] = x.get(
        "PRIOR_ROBUST_STRONG", pd.Series("NO", index=x.index)
    ).astype(str).str.upper().eq("YES")
    x["COLOC_STRONG_BOOL"] = x.get(
        "COLOCALIZED_STRONG", pd.Series("NO", index=x.index)
    ).astype(str).str.upper().eq("YES") | (
        x["FORMAL_VALID"] & (x["MAX_PP_H4"] >= strong_pp4)
    )
    x["COLOC_SUGGESTIVE_BOOL"] = (
        x["FORMAL_VALID"]
        & (x["MAX_PP_H4"] >= suggestive_pp4)
        & ~x["COLOC_STRONG_BOOL"]
    )

    mapped = x.apply(
        lambda row: map_coloc_gene(row, ens_to_symbol, symbol_to_ens),
        axis=1,
        result_type="expand",
    )
    mapped.columns = ["GENE_KEY", "GENE_ID_CANONICAL", "GENE_SYMBOL_CANONICAL"]
    x = pd.concat([x, mapped], axis=1)

    # Locus-level QTL evidence includes caQTL even when no target gene is known.
    locus_rows = []
    for (study, locus, qtl), g in x.groupby(
        ["STUDY_ACCESSION", "LOCUS_ID", "QTL_TYPE"], dropna=False, sort=False
    ):
        valid = g[g["FORMAL_VALID"]].copy()
        if not valid.empty and valid["MAX_PP_H4"].notna().any():
            idx = valid["MAX_PP_H4"].idxmax()
            best = valid.loc[idx]
            max_h4 = float(best["MAX_PP_H4"])
            max_h3 = float(best["MAX_PP_H3"]) if pd.notna(best["MAX_PP_H3"]) else np.nan
            best_gene = str(best.get("GENE_SYMBOL_CANONICAL", "")) or str(best.get("GENE_ID_CANONICAL", ""))
            best_gene_id = str(best.get("GENE_ID_CANONICAL", ""))
            best_tissue = str(best.get("TISSUE", ""))
            best_trait = str(best.get("MOLECULAR_TRAIT_ID", ""))
            best_dataset = str(best.get("DATASET", ""))
        else:
            max_h4 = np.nan
            max_h3 = np.nan
            best_gene = best_gene_id = best_tissue = best_trait = best_dataset = ""
        locus_rows.append({
            "STUDY_ACCESSION": study,
            "LOCUS_ID": locus,
            "QTL_TYPE": str(qtl),
            "N_CANDIDATE_ROWS": len(g),
            "N_FORMALLY_TESTED": int(g["FORMAL_VALID"].sum()),
            "N_STRONG": int((g["FORMAL_VALID"] & g["COLOC_STRONG_BOOL"]).sum()),
            "N_SUGGESTIVE": int((g["FORMAL_VALID"] & g["COLOC_SUGGESTIVE_BOOL"]).sum()),
            "N_PRIOR_ROBUST_STRONG": int((g["FORMAL_VALID"] & g["PRIOR_ROBUST_BOOL"]).sum()),
            "MAX_PP_H4": max_h4,
            "MAX_PP_H3": max_h3,
            "BEST_GENE": best_gene,
            "BEST_GENE_ID": best_gene_id,
            "BEST_TISSUE": best_tissue,
            "BEST_TRAIT": best_trait,
            "BEST_DATASET": best_dataset,
        })
    locus_qtl = pd.DataFrame(locus_rows)

    gene_x = x[x["GENE_KEY"].astype(str).str.strip() != ""].copy()
    if gene_x.empty:
        return pd.DataFrame(), locus_qtl

    gene_rows = []
    for (study, locus, gene_key), g in gene_x.groupby(
        ["STUDY_ACCESSION", "LOCUS_ID", "GENE_KEY"], dropna=False, sort=False
    ):
        row = {
            "STUDY_ACCESSION": study,
            "LOCUS_ID": locus,
            "GENE_KEY": gene_key,
            "GENE_ID_COLOC": str(first_nonempty(g["GENE_ID_CANONICAL"].tolist())),
            "GENE_SYMBOL_COLOC": str(first_nonempty(g["GENE_SYMBOL_CANONICAL"].tolist())),
            "N_COLOC_CANDIDATES": len(g),
            "N_FORMALLY_TESTED": int(g["FORMAL_VALID"].sum()),
            "N_STRONG_COLOC_ROWS": int((g["FORMAL_VALID"] & g["COLOC_STRONG_BOOL"]).sum()),
            "N_SUGGESTIVE_COLOC_ROWS": int((g["FORMAL_VALID"] & g["COLOC_SUGGESTIVE_BOOL"]).sum()),
            "ANY_PRIOR_ROBUST_STRONG": bool((g["FORMAL_VALID"] & g["PRIOR_ROBUST_BOOL"]).any()),
        }

        strong_types = []
        suggestive_types = []
        tested_types = []
        max_pp4_all = []

        for qtl_type in sorted(g["QTL_TYPE"].fillna("").astype(str).unique()):
            if not qtl_type:
                continue
            q = g[g["QTL_TYPE"].astype(str) == qtl_type].copy()
            valid = q[q["FORMAL_VALID"]].copy()
            qkey = re.sub(r"[^A-Za-z0-9]+", "_", qtl_type).upper().strip("_")
            if valid.empty or not valid["MAX_PP_H4"].notna().any():
                row[f"{qkey}_PP4"] = np.nan
                row[f"{qkey}_PP3"] = np.nan
                row[f"{qkey}_TISSUE"] = ""
                row[f"{qkey}_TRAIT"] = ""
                row[f"{qkey}_STRONG"] = False
                row[f"{qkey}_SUGGESTIVE"] = False
                row[f"{qkey}_PRIOR_ROBUST"] = False
                continue
            idx = valid["MAX_PP_H4"].idxmax()
            best = valid.loc[idx]
            pp4 = float(best["MAX_PP_H4"])
            pp3 = float(best["MAX_PP_H3"]) if pd.notna(best["MAX_PP_H3"]) else np.nan
            is_strong = bool(valid["COLOC_STRONG_BOOL"].any())
            is_suggestive = bool(valid["COLOC_SUGGESTIVE_BOOL"].any())
            is_robust = bool(valid["PRIOR_ROBUST_BOOL"].any())
            row[f"{qkey}_PP4"] = pp4
            row[f"{qkey}_PP3"] = pp3
            row[f"{qkey}_TISSUE"] = str(best.get("TISSUE", ""))
            row[f"{qkey}_TRAIT"] = str(best.get("MOLECULAR_TRAIT_ID", ""))
            row[f"{qkey}_DATASET"] = str(best.get("DATASET", ""))
            row[f"{qkey}_STRONG"] = is_strong
            row[f"{qkey}_SUGGESTIVE"] = is_suggestive
            row[f"{qkey}_PRIOR_ROBUST"] = is_robust
            tested_types.append(qtl_type)
            if is_strong:
                strong_types.append(qtl_type)
            elif is_suggestive:
                suggestive_types.append(qtl_type)
            max_pp4_all.append(pp4)

        row["FORMALLY_TESTED_QTL_TYPES"] = ";".join(tested_types)
        row["STRONG_QTL_TYPES"] = ";".join(strong_types)
        row["SUGGESTIVE_QTL_TYPES"] = ";".join(suggestive_types)
        row["N_STRONG_QTL_TYPES"] = len(set(strong_types))
        row["N_SUGGESTIVE_QTL_TYPES"] = len(set(suggestive_types))
        row["MAX_PP4"] = max(max_pp4_all) if max_pp4_all else np.nan
        gene_rows.append(row)

    return pd.DataFrame(gene_rows), locus_qtl


# =============================================================================
# INTERNAL GENE PRIORITISATION
# =============================================================================

def outer_merge_gene_evidence(variant_gene: pd.DataFrame,
                              coloc_gene: pd.DataFrame) -> pd.DataFrame:
    keys = ["STUDY_ACCESSION", "LOCUS_ID", "GENE_KEY"]
    if variant_gene.empty and coloc_gene.empty:
        return pd.DataFrame()
    if variant_gene.empty:
        x = coloc_gene.copy()
    elif coloc_gene.empty:
        x = variant_gene.copy()
    else:
        x = variant_gene.merge(coloc_gene, on=keys, how="outer", validate="one_to_one")

    x["GENE_ID"] = [
        str(first_nonempty([row.get("GENE_ID", ""), row.get("GENE_ID_COLOC", "")]))
        for _, row in x.iterrows()
    ]
    x["GENE_SYMBOL"] = [
        str(first_nonempty([row.get("GENE_SYMBOL", ""), row.get("GENE_SYMBOL_COLOC", "")]))
        for _, row in x.iterrows()
    ]
    x["GENE_DISPLAY"] = [
        str(first_nonempty([row.get("GENE_SYMBOL", ""), row.get("GENE_ID", ""), row.get("GENE_KEY", "")]))
        for _, row in x.iterrows()
    ]

    numeric_defaults = {
        "MAX_PIP": np.nan,
        "N_95CS_GENE_VARIANTS": 0,
        "N_GENE_LINKED_VARIANTS": 0,
        "MAX_SPLICEAI_DS": np.nan,
        "MAX_PANGOLIN_ABS": np.nan,
        "MAX_SPLICE_EVIDENCE_SOURCES": 0,
        "N_STRONG_QTL_TYPES": 0,
        "N_SUGGESTIVE_QTL_TYPES": 0,
        "N_FORMALLY_TESTED": 0,
        "MAX_PP4": np.nan,
    }
    for col, default in numeric_defaults.items():
        if col not in x.columns:
            x[col] = default
        x[col] = pd.to_numeric(x[col], errors="coerce")

    bool_defaults = {
        "ANY_PANGOLIN_TOP5": False,
        "ANY_PRIOR_ROBUST_STRONG": False,
    }
    for col, default in bool_defaults.items():
        if col not in x.columns:
            x[col] = default
        x[col] = bool_series(x[col])

    for col in ["BEST_FUNCTIONAL_CATEGORY", "BEST_IMPACT", "STRONG_QTL_TYPES", "SUGGESTIVE_QTL_TYPES"]:
        if col not in x.columns:
            x[col] = ""
        x[col] = x[col].fillna("").astype(str)

    return x


def assign_evidence_tier(row: pd.Series) -> str:
    strong_types = safe_int0(row.get("N_STRONG_QTL_TYPES", 0))
    sugg_types = safe_int0(row.get("N_SUGGESTIVE_QTL_TYPES", 0))
    robust = boolish(row.get("ANY_PRIOR_ROBUST_STRONG", False))
    pip = row.get("MAX_PIP", np.nan)
    pip = float(pip) if pd.notna(pip) else np.nan
    category = str(row.get("BEST_FUNCTIONAL_CATEGORY", "")).upper()
    impact = str(row.get("BEST_IMPACT", "")).upper()
    spliceai = row.get("MAX_SPLICEAI_DS", np.nan)
    spliceai = float(spliceai) if pd.notna(spliceai) else np.nan
    pang_top5 = boolish(row.get("ANY_PANGOLIN_TOP5", False))
    nsplice = safe_int0(row.get("MAX_SPLICE_EVIDENCE_SOURCES", 0))

    damaging_coding = (
        category in {"CODING", "SPLICING"}
        and impact in {"HIGH", "MODERATE"}
        and pd.notna(pip) and pip >= 0.10
    )

    if robust or strong_types >= 2 or (strong_types >= 1 and pd.notna(pip) and pip >= 0.10) or damaging_coding:
        return "TIER1_HIGH"

    if (
        strong_types >= 1
        or (sugg_types >= 1 and pd.notna(pip) and pip >= 0.01)
        or (pd.notna(spliceai) and spliceai >= 0.50 and pd.notna(pip) and pip >= 0.01)
        or (pang_top5 and pd.notna(pip) and pip >= 0.01)
        or (nsplice >= 2 and pd.notna(pip) and pip >= 0.01)
    ):
        return "TIER2_MODERATE"

    if sugg_types >= 1 or (pd.notna(pip) and pip >= 0.01) or category in {"CODING", "SPLICING", "REGULATORY"}:
        return "TIER3_SUPPORTING"

    return "TIER4_WEAK"


def mechanism_from_row(row: pd.Series) -> str:
    strong = {x.lower() for x in split_tokens(row.get("STRONG_QTL_TYPES", ""))}
    suggestive = {x.lower() for x in split_tokens(row.get("SUGGESTIVE_QTL_TYPES", ""))}
    category = str(row.get("BEST_FUNCTIONAL_CATEGORY", "")).upper()
    spliceai = row.get("MAX_SPLICEAI_DS", np.nan)
    spliceai = float(spliceai) if pd.notna(spliceai) else np.nan
    nsplice = safe_int0(row.get("MAX_SPLICE_EVIDENCE_SOURCES", 0))

    mechanisms = []
    if "eqtl" in strong:
        mechanisms.append("EXPRESSION_REGULATION")
    if "sqtl" in strong:
        mechanisms.append("SPLICING_REGULATION")
    if "pqtl" in strong:
        mechanisms.append("PROTEIN_ABUNDANCE")
    if "caqtl" in strong:
        mechanisms.append("CHROMATIN_REGULATION")
    if "meqtl" in strong or "mqtl" in strong:
        mechanisms.append("DNA_METHYLATION_REGULATION")
    if "hqtl" in strong:
        mechanisms.append("HISTONE_REGULATION")

    if category == "CODING":
        mechanisms.append("CODING_VARIANT")
    if category == "SPLICING" or (pd.notna(spliceai) and spliceai >= 0.50) or nsplice >= 2:
        mechanisms.append("PREDICTED_SPLICING")
    if category == "REGULATORY" and "CHROMATIN_REGULATION" not in mechanisms:
        mechanisms.append("REGULATORY_VARIANT")

    if not mechanisms and suggestive:
        for qtl in sorted(suggestive):
            label = {
                "eqtl": "SUGGESTIVE_EXPRESSION_REGULATION",
                "sqtl": "SUGGESTIVE_SPLICING_REGULATION",
                "pqtl": "SUGGESTIVE_PROTEIN_ABUNDANCE",
                "caqtl": "SUGGESTIVE_CHROMATIN_REGULATION",
            }.get(qtl, f"SUGGESTIVE_{qtl.upper()}")
            mechanisms.append(label)

    if not mechanisms:
        if category:
            mechanisms.append(f"ANNOTATION_{category}")
        else:
            mechanisms.append("GENE_LINK_WITHOUT_RESOLVED_MECHANISM")

    # Preserve order, remove duplicates.
    unique = []
    for m in mechanisms:
        if m not in unique:
            unique.append(m)
    return ";".join(unique)


def ranking_reason(row: pd.Series) -> str:
    parts = []
    if boolish(row.get("ANY_PRIOR_ROBUST_STRONG", False)):
        parts.append("prior-robust formal coloc")
    strong = split_tokens(row.get("STRONG_QTL_TYPES", ""))
    suggestive = split_tokens(row.get("SUGGESTIVE_QTL_TYPES", ""))
    if strong:
        parts.append("strong coloc: " + ",".join(strong))
    elif suggestive:
        parts.append("suggestive coloc: " + ",".join(suggestive))
    pip = row.get("MAX_PIP", np.nan)
    if pd.notna(pip):
        parts.append(f"max PIP={float(pip):.3g}")
    cat = str(row.get("BEST_FUNCTIONAL_CATEGORY", "")).strip()
    impact = str(row.get("BEST_IMPACT", "")).strip()
    if cat:
        parts.append(f"VEP={cat}" + (f"/{impact}" if impact else ""))
    sai = row.get("MAX_SPLICEAI_DS", np.nan)
    if pd.notna(sai) and float(sai) >= 0.20:
        parts.append(f"SpliceAI={float(sai):.3g}")
    if boolish(row.get("ANY_PANGOLIN_TOP5", False)):
        parts.append("Pangolin top-5%")
    nsp = safe_int0(row.get("MAX_SPLICE_EVIDENCE_SOURCES", 0))
    if nsp >= 2:
        parts.append(f"splice sources={nsp}")
    return "; ".join(parts) if parts else "weak/limited internal evidence"


def rank_genes(gene_evidence: pd.DataFrame) -> pd.DataFrame:
    if gene_evidence.empty:
        return gene_evidence
    x = gene_evidence.copy()
    x["EVIDENCE_TIER"] = x.apply(assign_evidence_tier, axis=1)
    x["TIER_RANK"] = x["EVIDENCE_TIER"].map(TIER_RANK).fillna(99).astype(int)
    x["DOMINANT_MECHANISM"] = x.apply(mechanism_from_row, axis=1)
    x["RANKING_REASON"] = x.apply(ranking_reason, axis=1)

    # Sorting metrics; no opaque weighted score.
    x["_ROBUST"] = bool_series(x["ANY_PRIOR_ROBUST_STRONG"]).astype(int)
    x["_MAX_PP4"] = pd.to_numeric(x["MAX_PP4"], errors="coerce").fillna(-1.0)
    x["_MAX_PIP"] = pd.to_numeric(x["MAX_PIP"], errors="coerce").fillna(-1.0)
    x["_FUNC_RANK"] = x["BEST_FUNCTIONAL_CATEGORY"].str.upper().map(FUNCTIONAL_CATEGORY_RANK).fillna(99)
    x["_IMPACT_RANK"] = x["BEST_IMPACT"].str.upper().map(IMPACT_RANK).fillna(99)
    x["_SPLICE"] = pd.to_numeric(x["MAX_SPLICE_EVIDENCE_SOURCES"], errors="coerce").fillna(0)

    x = x.sort_values(
        [
            "STUDY_ACCESSION", "LOCUS_ID", "TIER_RANK",
            "N_STRONG_QTL_TYPES", "_ROBUST", "_MAX_PP4", "_MAX_PIP",
            "_FUNC_RANK", "_IMPACT_RANK", "_SPLICE", "GENE_DISPLAY",
        ],
        ascending=[True, True, True, False, False, False, False, True, True, False, True],
        kind="stable",
    ).reset_index(drop=True)
    x["GENE_RANK"] = x.groupby(["STUDY_ACCESSION", "LOCUS_ID"], sort=False).cumcount() + 1
    return x.drop(columns=["_ROBUST", "_MAX_PP4", "_MAX_PIP", "_FUNC_RANK", "_IMPACT_RANK", "_SPLICE"])


# =============================================================================
# LOCUS SUMMARY
# =============================================================================

def normalize_locus_definitions(loci: pd.DataFrame, accession: str) -> pd.DataFrame:
    if loci.empty:
        return loci
    x = loci.copy()
    if "STUDY_ACCESSION" not in x.columns:
        x["STUDY_ACCESSION"] = accession
    x["STUDY_ACCESSION"] = accession
    for col in ["LOCUS_START", "LOCUS_END"]:
        if col in x.columns:
            x[col] = pd.to_numeric(x[col], errors="coerce")
    if "CHR" in x.columns:
        x["CHR"] = x["CHR"].map(canonical_chr)
    return x


def qtl_wide_for_locus(locus_qtl: pd.DataFrame) -> pd.DataFrame:
    if locus_qtl.empty:
        return pd.DataFrame()
    rows = []
    for (study, locus), g in locus_qtl.groupby(["STUDY_ACCESSION", "LOCUS_ID"], sort=False):
        row = {"STUDY_ACCESSION": study, "LOCUS_ID": locus}
        for _, q in g.iterrows():
            qtype = re.sub(r"[^A-Za-z0-9]+", "_", str(q["QTL_TYPE"])).upper().strip("_")
            row[f"BEST_{qtype}_PP4"] = q.get("MAX_PP_H4", np.nan)
            row[f"BEST_{qtype}_PP3"] = q.get("MAX_PP_H3", np.nan)
            row[f"BEST_{qtype}_GENE"] = q.get("BEST_GENE", "")
            row[f"BEST_{qtype}_GENE_ID"] = q.get("BEST_GENE_ID", "")
            row[f"BEST_{qtype}_TISSUE"] = q.get("BEST_TISSUE", "")
            row[f"BEST_{qtype}_TRAIT"] = q.get("BEST_TRAIT", "")
            row[f"N_{qtype}_TESTED"] = q.get("N_FORMALLY_TESTED", 0)
            row[f"N_{qtype}_STRONG"] = q.get("N_STRONG", 0)
            row[f"N_{qtype}_SUGGESTIVE"] = q.get("N_SUGGESTIVE", 0)
            row[f"N_{qtype}_PRIOR_ROBUST"] = q.get("N_PRIOR_ROBUST_STRONG", 0)
        rows.append(row)
    return pd.DataFrame(rows)


def variant_locus_metrics(variants: pd.DataFrame) -> pd.DataFrame:
    if variants.empty:
        return pd.DataFrame()
    rows = []
    for (study, locus), g in variants.groupby(["STUDY_ACCESSION", "LOCUS_ID"], dropna=False, sort=False):
        pip = pd.to_numeric(g.get("PIP", pd.Series(np.nan, index=g.index)), errors="coerce")
        sai = pd.to_numeric(g.get("SPLICEAI_MAX_DS", pd.Series(np.nan, index=g.index)), errors="coerce")
        pang = pd.to_numeric(g.get("PANGOLIN_MAX_ABS", pd.Series(np.nan, index=g.index)), errors="coerce")
        top_variant = ""
        top_reference = ""
        top_category = ""
        top_impact = ""
        if pip.notna().any():
            idx = pip.idxmax()
            top_variant = str(g.loc[idx, "VARIANT_KEY"])
            top_reference = str(g.loc[idx].get("REFERENCE_ID", ""))
            top_category = str(g.loc[idx].get("FUNCTIONAL_CATEGORY", ""))
            top_impact = str(g.loc[idx].get("IMPACT", ""))
        rows.append({
            "STUDY_ACCESSION": study,
            "LOCUS_ID": locus,
            "N_VARIANTS_IN_MASTER": int(g["VARIANT_KEY"].replace("", np.nan).nunique()),
            "MAX_LOCUS_PIP": pip.max() if pip.notna().any() else np.nan,
            "TOP_PIP_VARIANT": top_variant,
            "TOP_PIP_REFERENCE_ID": top_reference,
            "TOP_PIP_FUNCTIONAL_CATEGORY": top_category,
            "TOP_PIP_IMPACT": top_impact,
            "MAX_LOCUS_SPLICEAI": sai.max() if sai.notna().any() else np.nan,
            "MAX_LOCUS_PANGOLIN": pang.max() if pang.notna().any() else np.nan,
        })
    return pd.DataFrame(rows)


def build_locus_summary(loci_all: pd.DataFrame, ranked: pd.DataFrame,
                        locus_qtl: pd.DataFrame, variants: pd.DataFrame,
                        step11_status: pd.DataFrame) -> pd.DataFrame:
    base = loci_all.copy()
    if base.empty:
        return pd.DataFrame()

    top_rows = []
    if not ranked.empty:
        for (study, locus), g in ranked.groupby(["STUDY_ACCESSION", "LOCUS_ID"], sort=False):
            g = g.sort_values("GENE_RANK")
            top = g.iloc[0]
            top3 = g.head(3)
            top_rows.append({
                "STUDY_ACCESSION": study,
                "LOCUS_ID": locus,
                "N_CANDIDATE_GENES": len(g),
                "TOP_GENE": top.get("GENE_DISPLAY", ""),
                "TOP_GENE_ID": top.get("GENE_ID", ""),
                "TOP_GENE_TIER": top.get("EVIDENCE_TIER", ""),
                "TOP_GENE_MECHANISM": top.get("DOMINANT_MECHANISM", ""),
                "TOP_GENE_REASON": top.get("RANKING_REASON", ""),
                "TOP_GENE_MAX_PIP": top.get("MAX_PIP", np.nan),
                "TOP_GENE_MAX_PP4": top.get("MAX_PP4", np.nan),
                "TOP3_GENES": ";".join(top3["GENE_DISPLAY"].astype(str).tolist()),
            })
    top_df = pd.DataFrame(top_rows)

    qwide = qtl_wide_for_locus(locus_qtl)
    vmetrics = variant_locus_metrics(variants)

    x = base.copy()
    for other in [top_df, qwide, vmetrics, step11_status]:
        if other is not None and not other.empty:
            keys = ["STUDY_ACCESSION", "LOCUS_ID"]
            keep = [c for c in other.columns if c not in x.columns or c in keys]
            x = x.merge(other[keep], on=keys, how="left")

    def classify(row: pd.Series) -> tuple[str, str]:
        step11 = str(row.get("STATUS", ""))
        top_gene = str(row.get("TOP_GENE", "")).strip()
        tier = str(row.get("TOP_GENE_TIER", ""))
        ca_pp4 = row.get("BEST_CAQTL_PP4", np.nan)
        ca_gene = str(row.get("BEST_CAQTL_GENE", "")).strip()
        strong_ca = pd.notna(ca_pp4) and float(ca_pp4) >= DEFAULT_STRONG_PP4
        n_tested = pd.to_numeric(pd.Series([row.get("N_TESTED", np.nan)]), errors="coerce").iloc[0]
        n_resource_errors = pd.to_numeric(pd.Series([row.get("N_RESOURCE_ERRORS", np.nan)]), errors="coerce").iloc[0]
        n_resource_unavailable = pd.to_numeric(pd.Series([row.get("N_RESOURCE_UNAVAILABLE", np.nan)]), errors="coerce").iloc[0]

        if step11 in {"FAILED", "NOT_TESTED_RESOURCE_UNAVAILABLE", "TIME_BUDGET_EXCEEDED"}:
            return "NOT_FULLY_INTERPRETABLE", f"STEP11_{step11}"
        if (
            (pd.isna(n_tested) or float(n_tested) == 0.0)
            and (
                (pd.notna(n_resource_errors) and float(n_resource_errors) > 0.0)
                or (pd.notna(n_resource_unavailable) and float(n_resource_unavailable) > 0.0)
            )
        ):
            return "NOT_FULLY_INTERPRETABLE", "STEP11_RESOURCE_FAILURE_WITHOUT_FORMAL_TEST"
        if top_gene and tier == "TIER1_HIGH":
            return "INTERPRETED_HIGH", str(row.get("TOP_GENE_MECHANISM", ""))
        if top_gene and tier == "TIER2_MODERATE":
            return "INTERPRETED_MODERATE", str(row.get("TOP_GENE_MECHANISM", ""))
        if top_gene:
            return "INTERPRETED_SUPPORTING", str(row.get("TOP_GENE_MECHANISM", ""))
        if strong_ca and not ca_gene:
            return "GENE_UNRESOLVED_REGULATORY", "CHROMATIN_REGULATION_WITHOUT_TARGET_GENE"
        return "UNRESOLVED", "NO_DEFENSIBLE_GENE_OR_MECHANISM"

    classes = x.apply(classify, axis=1, result_type="expand")
    classes.columns = ["LOCUS_INTERPRETATION_STATUS", "LOCUS_MECHANISM"]
    x = pd.concat([x, classes], axis=1)

    preferred = [
        "STUDY_ACCESSION", "LOCUS_ID", "CHR", "LOCUS_START", "LOCUS_END",
        "LEAD_IDS", "LEAD_POSITIONS", "MIN_LEAD_P",
        "LOCUS_INTERPRETATION_STATUS", "TOP_GENE", "TOP_GENE_ID",
        "TOP_GENE_TIER", "TOP_GENE_MECHANISM", "TOP_GENE_REASON", "TOP3_GENES",
        "TOP_GENE_MAX_PIP", "TOP_GENE_MAX_PP4",
        "TOP_PIP_VARIANT", "TOP_PIP_REFERENCE_ID", "TOP_PIP_FUNCTIONAL_CATEGORY",
        "MAX_LOCUS_PIP", "MAX_LOCUS_SPLICEAI", "MAX_LOCUS_PANGOLIN",
        "BEST_EQTL_PP4", "BEST_EQTL_GENE", "BEST_EQTL_TISSUE",
        "BEST_SQTL_PP4", "BEST_SQTL_GENE", "BEST_SQTL_TISSUE",
        "BEST_PQTL_PP4", "BEST_PQTL_GENE", "BEST_PQTL_TISSUE",
        "BEST_CAQTL_PP4", "BEST_CAQTL_GENE", "BEST_CAQTL_TISSUE",
        "LOCUS_MECHANISM", "STATUS", "N_TESTED", "N_RESOURCE_ERRORS",
        "N_RESOURCE_UNAVAILABLE",
    ]
    front = [c for c in preferred if c in x.columns]
    rest = [c for c in x.columns if c not in front]
    return x[front + rest]


# =============================================================================
# PHENOTYPE CONSENSUS LOCI / PATHWAY INPUT
# =============================================================================

def parse_first_lead_position(value) -> float:
    vals = re.findall(r"\d+", str(value))
    return float(vals[0]) if vals else np.nan


def reciprocal_overlap(a1: float, a2: float, b1: float, b2: float) -> float:
    inter = max(0.0, min(a2, b2) - max(a1, b1) + 1.0)
    if inter <= 0:
        return 0.0
    la = max(1.0, a2 - a1 + 1.0)
    lb = max(1.0, b2 - b1 + 1.0)
    return min(inter / la, inter / lb)


def build_consensus_loci(locus_summary: pd.DataFrame,
                         min_recip_overlap: float,
                         lead_distance_bp: int) -> pd.DataFrame:
    if locus_summary.empty:
        return pd.DataFrame()
    req = {"CHR", "LOCUS_START", "LOCUS_END"}
    if not req.issubset(locus_summary.columns):
        return pd.DataFrame()

    x = locus_summary.copy()
    x["LOCUS_START"] = pd.to_numeric(x["LOCUS_START"], errors="coerce")
    x["LOCUS_END"] = pd.to_numeric(x["LOCUS_END"], errors="coerce")
    x["CHR"] = x["CHR"].map(canonical_chr)
    x["_LEAD"] = x.get("LEAD_POSITIONS", pd.Series("", index=x.index)).map(parse_first_lead_position)
    x = x.dropna(subset=["LOCUS_START", "LOCUS_END"])

    # Union-find over loci meeting either reciprocal-overlap or lead-distance rule.
    n = len(x)
    parent = list(range(n))

    def find(i):
        while parent[i] != i:
            parent[i] = parent[parent[i]]
            i = parent[i]
        return i

    def union(i, j):
        ri, rj = find(i), find(j)
        if ri != rj:
            parent[rj] = ri

    records = x.reset_index(drop=True)
    for chrom, idxs in records.groupby("CHR").groups.items():
        idxs = list(idxs)
        for ii, i in enumerate(idxs):
            a = records.loc[i]
            for j in idxs[ii + 1:]:
                b = records.loc[j]
                if float(b["LOCUS_START"]) > float(a["LOCUS_END"]) + lead_distance_bp:
                    # sortedness is not guaranteed globally, so do not break.
                    pass
                ro = reciprocal_overlap(
                    float(a["LOCUS_START"]), float(a["LOCUS_END"]),
                    float(b["LOCUS_START"]), float(b["LOCUS_END"]),
                )
                lead_close = (
                    pd.notna(a["_LEAD"]) and pd.notna(b["_LEAD"])
                    and abs(float(a["_LEAD"]) - float(b["_LEAD"])) <= lead_distance_bp
                )
                if ro >= min_recip_overlap or lead_close:
                    union(i, j)

    groups = defaultdict(list)
    for i in range(n):
        groups[find(i)].append(i)

    rows = []
    ordered = sorted(groups.values(), key=lambda members: (
        records.loc[members[0], "CHR"],
        float(records.loc[members, "LOCUS_START"].min()),
    ))
    for number, members in enumerate(ordered, start=1):
        g = records.loc[members].copy()
        top_genes = [x for x in g.get("TOP_GENE", pd.Series("", index=g.index)).astype(str) if x]
        mechanisms = join_unique(g.get("LOCUS_MECHANISM", pd.Series("", index=g.index)))
        rows.append({
            "CONSENSUS_LOCUS_ID": f"CL{number:04d}",
            "CHR": str(g["CHR"].iloc[0]),
            "CONSENSUS_START": int(g["LOCUS_START"].min()),
            "CONSENSUS_END": int(g["LOCUS_END"].max()),
            "N_STUDY_LOCI": len(g),
            "N_STUDIES": g["STUDY_ACCESSION"].nunique(),
            "STUDY_LOCI": ";".join(
                f"{r.STUDY_ACCESSION}:{r.LOCUS_ID}" for r in g.itertuples(index=False)
            ),
            "TOP_GENES": ";".join(dict.fromkeys(top_genes)),
            "MECHANISMS": mechanisms,
            "BEST_TIER": min(
                [TIER_RANK.get(str(v), 99) for v in g.get("TOP_GENE_TIER", pd.Series("", index=g.index))],
                default=99,
            ),
            "INTERPRETATION_STATUSES": join_unique(
                g.get("LOCUS_INTERPRETATION_STATUS", pd.Series("", index=g.index))
            ),
        })
    out = pd.DataFrame(rows)
    if not out.empty:
        inv = {v: k for k, v in TIER_RANK.items()}
        out["BEST_TIER"] = out["BEST_TIER"].map(inv).fillna("UNRESOLVED")
    return out


def build_pathway_input(ranked: pd.DataFrame, max_tier_rank: int) -> pd.DataFrame:
    if ranked.empty:
        return pd.DataFrame()
    x = ranked[ranked["TIER_RANK"] <= max_tier_rank].copy()
    x = x[x["GENE_DISPLAY"].astype(str).str.strip() != ""]
    if x.empty:
        return pd.DataFrame()

    rows = []
    for gene, g in x.groupby("GENE_DISPLAY", sort=False):
        pp4 = pd.to_numeric(g.get("MAX_PP4", pd.Series(np.nan, index=g.index)), errors="coerce")
        pip = pd.to_numeric(g.get("MAX_PIP", pd.Series(np.nan, index=g.index)), errors="coerce")
        rows.append({
            "GENE": gene,
            "GENE_ID": str(first_nonempty(g.get("GENE_ID", pd.Series("", index=g.index)).tolist())),
            "BEST_TIER": g.sort_values("TIER_RANK")["EVIDENCE_TIER"].iloc[0],
            "N_STUDIES": g["STUDY_ACCESSION"].nunique(),
            "N_STUDY_LOCI": len(g[["STUDY_ACCESSION", "LOCUS_ID"]].drop_duplicates()),
            "STUDY_LOCI": ";".join(
                f"{r.STUDY_ACCESSION}:{r.LOCUS_ID}" for r in g[["STUDY_ACCESSION", "LOCUS_ID"]].drop_duplicates().itertuples(index=False)
            ),
            "MAX_PP4": pp4.max() if pp4.notna().any() else np.nan,
            "MAX_PIP": pip.max() if pip.notna().any() else np.nan,
            "MECHANISMS": join_unique(g["DOMINANT_MECHANISM"]),
            "STRONG_QTL_TYPES": join_unique(g["STRONG_QTL_TYPES"]),
            "SUGGESTIVE_QTL_TYPES": join_unique(g["SUGGESTIVE_QTL_TYPES"]),
        })
    out = pd.DataFrame(rows)
    if not out.empty:
        out["_TIER"] = out["BEST_TIER"].map(TIER_RANK).fillna(99)
        out = out.sort_values(
            ["_TIER", "N_STUDY_LOCI", "MAX_PP4", "MAX_PIP", "GENE"],
            ascending=[True, False, False, False, True],
            kind="stable",
        ).drop(columns="_TIER")
    return out


# =============================================================================
# MAIN
# =============================================================================

def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "GWAS2m Step12: integrate fine-mapping, functional/splicing evidence "
            "and strict Step11 molecular-QTL colocalisation into locus/gene/mechanism tables."
        )
    )
    parser.add_argument("--phenotype", required=True)
    parser.add_argument("--ancestry", required=True)
    parser.add_argument("--study", default=None)
    parser.add_argument("--strong-pp4", type=float, default=DEFAULT_STRONG_PP4)
    parser.add_argument("--suggestive-pp4", type=float, default=DEFAULT_SUGGESTIVE_PP4)
    parser.add_argument(
        "--allow-incomplete-step11", action="store_true",
        help="Exploratory only: permit FAILED/MISSING Step11 loci instead of stopping."
    )
    parser.add_argument(
        "--consensus-recip-overlap", type=float, default=0.25,
        help="Minimum reciprocal interval overlap to merge study-specific loci into phenotype consensus loci."
    )
    parser.add_argument(
        "--consensus-lead-distance-kb", type=int, default=500,
        help="Also merge loci when their first lead positions are within this distance."
    )
    parser.add_argument(
        "--pathway-max-tier", type=int, default=DEFAULT_MIN_PATHWAY_TIER,
        choices=[1, 2, 3, 4],
        help="Include genes through this tier rank in pathway_input_genes.tsv. Default: 2."
    )
    parser.add_argument("--max-print", type=int, default=200)
    args = parser.parse_args()

    if not (0 <= args.suggestive_pp4 <= 1 and 0 <= args.strong_pp4 <= 1):
        raise SystemExit("PP4 thresholds must be between 0 and 1")
    if args.strong_pp4 < args.suggestive_pp4:
        raise SystemExit("--strong-pp4 must be >= --suggestive-pp4")

    root = Path.cwd().resolve()
    phenotype = args.phenotype.strip()
    ancestry_code, ancestry_label = canonical_ancestry(args.ancestry)
    paths = make_paths(root, phenotype, ancestry_label)
    paths["OUT"].mkdir(parents=True, exist_ok=True)

    studies = discover_studies(paths, args.study)
    if not studies:
        raise SystemExit("No matching GCST studies found in GWAS2m outputs")

    banner("GWAS2m STEP12 - INTEGRATED LOCUS -> GENE -> MECHANISM")
    print(f"Phenotype : {phenotype}")
    print(f"Ancestry  : {ancestry_label} ({ancestry_code})")
    print(f"Studies   : {len(studies)}")
    print(f"Output    : {paths['OUT']}")
    print("Open Targets: NOT USED (reserved for independent downstream benchmarking)")

    audit_rows = []
    loci_frames = []
    variant_frames = []
    coloc_frames = []
    step11_status_frames = []

    for accession in studies:
        files = study_files(paths, accession)

        loci = read_table(files["S06_LOCI"], required=True)
        loci = normalize_locus_definitions(loci, accession)
        loci_frames.append(loci)

        variants, variant_source = load_best_variant_table(files, accession)
        if variants.empty:
            raise RuntimeError(
                f"No usable Step06-10 variant evidence for {accession}. "
                "Expected at least Step06 fine-mapped variants."
            )
        variant_frames.append(variants)

        status = step11_locus_statuses(paths, accession)
        step11_status_frames.append(status)

        expected_loci = set(loci["LOCUS_ID"].astype(str)) if "LOCUS_ID" in loci.columns else set()
        got_status = set(status["LOCUS_ID"].astype(str)) if not status.empty else set()
        missing_status = sorted(expected_loci - got_status)
        failed = status[status["STATUS"].astype(str).isin([
            "FAILED", "TIME_BUDGET_EXCEEDED", "NOT_TESTED_RESOURCE_UNAVAILABLE"
        ])] if not status.empty else pd.DataFrame()

        if not args.allow_incomplete_step11 and (missing_status or not failed.empty):
            details = []
            if missing_status:
                details.append("missing locus summaries=" + ",".join(missing_status))
            if not failed.empty:
                details.append(
                    "non-complete loci=" + ",".join(
                        f"{r.LOCUS_ID}:{r.STATUS}" for r in failed.itertuples(index=False)
                    )
                )
            raise RuntimeError(
                f"Step11 is not scientifically complete for {accession}: " + "; ".join(details) +
                ". Finish/rerun Step11 or use --allow-incomplete-step11 for exploratory inspection only."
            )

        coloc = load_formal_coloc_for_study(paths, accession)
        if not coloc.empty:
            coloc_frames.append(coloc)

        audit_rows.append({
            "STUDY_ACCESSION": accession,
            "N_LOCI": len(loci),
            "VARIANT_SOURCE": variant_source,
            "N_VARIANT_ROWS": len(variants),
            "N_STEP11_LOCUS_SUMMARIES": len(status),
            "N_STEP11_FAILED_OR_UNAVAILABLE": len(failed),
            "N_FORMAL_COLOC_ROWS": len(coloc),
            "S06_LOCI": str(files["S06_LOCI"] or ""),
            "S06_VARIANTS": str(files["S06_VARIANTS"] or ""),
            "S07_VARIANTS": str(files["S07_VARIANTS"] or ""),
            "S08_VARIANTS": str(files["S08_VARIANTS"] or ""),
            "S09_VARIANTS": str(files["S09_VARIANTS"] or ""),
            "S10_VARIANTS": str(files["S10_VARIANTS"] or ""),
            "S11_ROOT": str(files["S11_ROOT"] or ""),
        })

    loci_all = pd.concat(loci_frames, ignore_index=True, sort=False)
    variants_all = pd.concat(variant_frames, ignore_index=True, sort=False)
    coloc_all = pd.concat(coloc_frames, ignore_index=True, sort=False) if coloc_frames else pd.DataFrame()
    step11_status_all = pd.concat(step11_status_frames, ignore_index=True, sort=False) if step11_status_frames else pd.DataFrame()
    audit = pd.DataFrame(audit_rows)

    # Gene-level evidence.
    links = variant_gene_links(variants_all)
    variant_gene = aggregate_variant_gene_evidence(links)
    coloc_gene, locus_qtl = aggregate_coloc_gene_evidence(
        coloc_all, variants_all, args.strong_pp4, args.suggestive_pp4
    )
    gene_evidence = outer_merge_gene_evidence(variant_gene, coloc_gene)
    ranked = rank_genes(gene_evidence)

    locus_summary = build_locus_summary(
        loci_all, ranked, locus_qtl, variants_all, step11_status_all
    )

    unresolved = locus_summary[
        locus_summary["LOCUS_INTERPRETATION_STATUS"].astype(str).isin([
            "UNRESOLVED", "GENE_UNRESOLVED_REGULATORY", "NOT_FULLY_INTERPRETABLE"
        ])
    ].copy() if not locus_summary.empty else pd.DataFrame()

    consensus = build_consensus_loci(
        locus_summary,
        min_recip_overlap=args.consensus_recip_overlap,
        lead_distance_bp=args.consensus_lead_distance_kb * 1000,
    )
    pathway_input = build_pathway_input(ranked, args.pathway_max_tier)

    # Save everything.
    out = paths["OUT"]
    variants_all.to_csv(
        out / "all_variant_evidence.tsv.gz", sep="\t", index=False, compression="gzip"
    )
    coloc_all.to_csv(out / "formal_coloc_all.tsv", sep="\t", index=False)
    gene_evidence.to_csv(out / "all_gene_evidence.tsv", sep="\t", index=False)
    ranked.to_csv(out / "prioritized_genes.tsv", sep="\t", index=False)
    locus_summary.to_csv(out / "locus_mechanism_summary.tsv", sep="\t", index=False)
    unresolved.to_csv(out / "unresolved_loci.tsv", sep="\t", index=False)
    consensus.to_csv(out / "phenotype_consensus_loci.tsv", sep="\t", index=False)
    pathway_input.to_csv(out / "pathway_input_genes.tsv", sep="\t", index=False)
    audit.to_csv(out / "step12_input_audit.tsv", sep="\t", index=False)

    summary = {
        "STEP12_VERSION": STEP12_VERSION,
        "PHENOTYPE": phenotype,
        "ANCESTRY_CODE": ancestry_code,
        "ANCESTRY_LABEL": ancestry_label,
        "N_STUDIES": len(studies),
        "N_STUDY_LOCI": len(locus_summary),
        "N_VARIANT_ROWS": len(variants_all),
        "N_FORMAL_COLOC_ROWS": len(coloc_all),
        "N_GENE_EVIDENCE_ROWS": len(gene_evidence),
        "N_PRIORITIZED_GENE_ROWS": len(ranked),
        "N_TIER1_GENE_ROWS": int((ranked.get("EVIDENCE_TIER", pd.Series(dtype=str)) == "TIER1_HIGH").sum()) if not ranked.empty else 0,
        "N_TIER2_GENE_ROWS": int((ranked.get("EVIDENCE_TIER", pd.Series(dtype=str)) == "TIER2_MODERATE").sum()) if not ranked.empty else 0,
        "N_INTERPRETED_HIGH_LOCI": int((locus_summary.get("LOCUS_INTERPRETATION_STATUS", pd.Series(dtype=str)) == "INTERPRETED_HIGH").sum()) if not locus_summary.empty else 0,
        "N_INTERPRETED_MODERATE_LOCI": int((locus_summary.get("LOCUS_INTERPRETATION_STATUS", pd.Series(dtype=str)) == "INTERPRETED_MODERATE").sum()) if not locus_summary.empty else 0,
        "N_UNRESOLVED_LOCI": len(unresolved),
        "N_CONSENSUS_LOCI": len(consensus),
        "N_PATHWAY_INPUT_GENES": len(pathway_input),
        "STRONG_PP4": args.strong_pp4,
        "SUGGESTIVE_PP4": args.suggestive_pp4,
        "ALLOW_INCOMPLETE_STEP11": bool(args.allow_incomplete_step11),
        "COMPLETED_UTC": utcnow(),
        "OUTPUT_DIR": str(out),
    }
    write_json(out / "step12_summary.json", summary)

    # -------------------------------------------------------------------------
    # SCREEN OUTPUT: the user explicitly requested the final table be printed.
    # -------------------------------------------------------------------------
    final_columns = [
        "STUDY_ACCESSION", "LOCUS_ID", "CHR", "LOCUS_START", "LOCUS_END",
        "LOCUS_INTERPRETATION_STATUS", "TOP_GENE", "TOP_GENE_TIER",
        "TOP_GENE_MECHANISM", "TOP_GENE_MAX_PIP", "TOP_GENE_MAX_PP4",
        "TOP_PIP_VARIANT", "TOP_PIP_FUNCTIONAL_CATEGORY",
        "BEST_EQTL_PP4", "BEST_EQTL_GENE", "BEST_EQTL_TISSUE",
        "BEST_SQTL_PP4", "BEST_SQTL_GENE", "BEST_SQTL_TISSUE",
        "BEST_PQTL_PP4", "BEST_PQTL_GENE", "BEST_PQTL_TISSUE",
        "BEST_CAQTL_PP4", "BEST_CAQTL_GENE", "BEST_CAQTL_TISSUE",
        "LOCUS_MECHANISM",
    ]
    show(
        locus_summary,
        "FINAL PHENOTYPE LOCUS -> GENE -> MECHANISM TABLE",
        final_columns,
        max_rows=args.max_print,
    )

    prioritized_columns = [
        "STUDY_ACCESSION", "LOCUS_ID", "GENE_RANK", "GENE_DISPLAY",
        "GENE_ID", "EVIDENCE_TIER", "DOMINANT_MECHANISM",
        "MAX_PIP", "MAX_PP4", "STRONG_QTL_TYPES", "SUGGESTIVE_QTL_TYPES",
        "BEST_FUNCTIONAL_CATEGORY", "BEST_IMPACT", "MAX_SPLICEAI_DS",
        "MAX_PANGOLIN_ABS", "RANKING_REASON",
    ]
    show(
        ranked,
        "RANKED GENES PER LOCUS",
        prioritized_columns,
        max_rows=args.max_print,
    )

    show(
        pathway_input,
        "GENES PASSED TO STEP13 PATHWAY/NETWORK ANALYSIS",
        [
            "GENE", "GENE_ID", "BEST_TIER", "N_STUDIES", "N_STUDY_LOCI",
            "MAX_PP4", "MAX_PIP", "MECHANISMS", "STRONG_QTL_TYPES",
        ],
        max_rows=args.max_print,
    )

    banner("STEP12 COMPLETE")
    print(f"Study-specific loci       : {len(locus_summary):,}")
    print(f"Gene evidence rows        : {len(ranked):,}")
    print(f"Tier-1 gene rows          : {summary['N_TIER1_GENE_ROWS']:,}")
    print(f"Tier-2 gene rows          : {summary['N_TIER2_GENE_ROWS']:,}")
    print(f"Unresolved loci           : {len(unresolved):,}")
    print(f"Phenotype consensus loci  : {len(consensus):,}")
    print(f"Pathway input genes       : {len(pathway_input):,}")
    print(f"\nSaved to:\n  {out}")
    print("\nKey files:")
    for name in [
        "locus_mechanism_summary.tsv",
        "prioritized_genes.tsv",
        "pathway_input_genes.tsv",
        "phenotype_consensus_loci.tsv",
        "unresolved_loci.tsv",
        "step12_summary.json",
    ]:
        print(f"  {out / name}")


if __name__ == "__main__":
    main()
